### ISSUE TITLE
ext_newgrid was renamed to ext_linegrid

### ISSUE THREAD

**Issue by bfredl** [vhakulinen/gnvim#1]
Just a headsup that nvim core renamed the new UI extension `ext_newgrid` (which this UI uses) to `ext_linegrid` on latest master. This UI will need to be changed to use the new name, sorry for the annoyance. Ref https://github.com/neovim/neovim/pull/9064

**Comment by vhakulinen** [comment]
Thanks for the headsup.

**Comment by vhakulinen** [comment]
Closed by e3d1fad82fb7c646ed9f69bd56a3a9dd17454d17
