### ISSUE TITLE
Synchronous commands after ui_attach

### ISSUE THREAD

**Issue by philipc** [vhakulinen/gnvim#10]
I've run into a couple of related issues. The problem seems to be that if synchronous commands are used after ui_attach, there's a possibility they will deadlock if nvim needs to get input from the user before proceeding (I know very little about the RPC interface). The cases I've run into are if there's an error in .vimrc, or if one of the files being edited has a swap file. The synchronous commands are:
- `nvim.command` for opening the files as tabs. Can these be appended to the nvim command line instead, with the usual `-p` option for tabs?
- `nvim.ui_try_resize`

Commenting out the code for these allows gnvim to proceed.

**Comment by vhakulinen** [comment]
This is somewhat a known issue currently and I haven't got around to fix it (or even figure out what to do with it). It has been painful to develop gnvim-lsp plugin, because an error wont even be displayed if it happens on startup... The initial fix would probably be to show some "waiting for neovim" view on gnivm startup, and if the RPC channel times out, show the output of nvim so user can see if there were any errors.

Those two examples you listed: are you talking about something that is happening inside gnvim's code or in some other plugin?

@bfredl didn't you guys fix the swap file issue already?

**Comment by philipc** [comment]
Inside gnvim,  `nvim.command` called [here](https://github.com/vhakulinen/gnvim/blob/b279ea69bf280aa2f8f57a10e408d6810f55ef82/src/main.rs#L117-L124), and `nvim.ui_try_resize` called [here](https://github.com/vhakulinen/gnvim/blob/b279ea69bf280aa2f8f57a10e408d6810f55ef82/src/ui/ui.rs#L147).

> The initial fix would probably be to show some "waiting for neovim" view on gnivm startup

I don't see how that fixes it. I think the problem is neovim is waiting for gnvim.

**Comment by philipc** [comment]
Looks like https://github.com/neovim/neovim/pull/9024 is meant to fix this.

**Comment by bfredl** [comment]
The condition for the new `--embed` semantics to work, is that after `ui_attach`, the UI must immediately be prepared to handle notifications and display them to the user, and immediately process user input and forward it to nvim. If the client does blocking calls after attach, it must still do all that above while waiting for the blocking call to return. Another solution is to do those requests asynchronously if waiting for them to finish is not necessary.

**Comment by bfredl** [comment]
See also the note at `:help ui-startup` for doing synchronous UI setup at VimEnter. Also ideally `ui_try_resize` shouldn't be done immediately affer `ui_attach`, it would be better to defer the attach until the client knows what size to use.

**Comment by vhakulinen** [comment]
> I don't see how that fixes it. I think the problem is neovim is waiting for gnvim.

It wouldn't fix those cases within gnvim's code, but would allow user to see if neovim exited out. I'll have to have deep dive on the things @bfredl mentioned. There is also ongoing effort to fix some stuff with `neovim-lib` (library gnvim is using) to fix some dead lock situations, but I'm not sure if this case is related to that.

**Comment by vhakulinen** [comment]
> ...Can these be appended to the nvim command line instead, with the usual -p option for tabs?

I didn't even consider this when I implemented the default to open files from arguments in tabs. This sounds much better option.

**Comment by vhakulinen** [comment]
@philipc can you try #15? It should fix this issue, but leaves room for improvement. The ui_attach call should be postponed to the moment when we know the size of our window.

**Comment by philipc** [comment]
Yes that fixes the deadlock.
