### ISSUE TITLE
Panic opening folder

### ISSUE THREAD

**Issue by badosu** [vhakulinen/gnvim#104]
Just installed gnvim on a new machine, it panics when opening a folder with netrw.

Will provide a better backtrace later: [without debug symbols](https://gist.github.com/badosu/ac9e128e544a7a0bc98278c635f81858).

**Comment by vhakulinen** [comment]
Which nvim version do you have?

**Comment by elihunter173** [comment]
Duplicate of #43?

**Comment by vhakulinen** [comment]
> Duplicate of #43?

Likely.

**Comment by badosu** [comment]
Thanks for checking, I believe so too!

**Comment by badosu** [comment]
> Which nvim version do you have?

Will check when I have access to the machine again.
