### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by clason** [vhakulinen/gnvim#107]
Currently gnvim prints a lot of status information to the console via simple `println`, which is useful for debugging, but kind of distracting for production use. Would it be possible to redirect those to `stderr` instead, or at least reserve the `println`s for a debug build?

**Comment by smolck** [comment]
This is probably a good idea. #67 was a failed attempt of mine at this, but it wasn’t the right way of doing things IMO. The way [neovim-gtk](https://github.com/daa84/neovim-gtk) does it is probably one of (if not the) best way of doing what you speak of. Over there they fork the process (on *nix) to the background when you run neovim-gtk, and the output goes to a file in `/tmp` it appears; see [this line in `main.rs` of neovim-gtk](https://github.com/daa84/neovim-gtk/blob/6b0687d080b5959cd41073f131cc8539ea7d96ef/src/main.rs#L91).

We could do something like neovim-gtk does, although that’s not the best for debugging IMO. Conditional compilation would be nice, but I feel it can add a lot of noise to the code when done the wrong way (as I showed with #67). We could do a `macro_rules!` macro which prints errors to `stderr` in production builds but to `stdout` in debug builds, but that may be unnecessary.

**Comment by clason** [comment]
Maybe put the fork behind a debug (or rather, release/non-debug) flag? Then you should have the same behavior, but only a single place where it is toggled (which I assume was your main issue with #67).

**Comment by smolck** [comment]
I’m not quite sure I understand what you mean when you say to put the fork behind a debug flag. Could you elaborate?

**Comment by clason** [comment]
I probably didn't think this through enough, but I meant only doing what `neovim-gtk` does for a release build, otherwise start the `nvim` instance as now. (Which assumes that this choice does not affect how `gnvim` interacts with `nvim`.)

**Comment by smolck** [comment]
I like that idea better than a macro for sure! Shouldn’t change anything about GNvim’s interactions with nvim either. @vhakulinen Do you like this idea? If so I can start work on a PR once I get the chance.

**Comment by vhakulinen** [comment]
Improving log output and forking the process are two different issues. For log improvements, I would like to see a macro (or something) that gets removed on release builds.

**Comment by smolck** [comment]
> For log improvements, I would like to see a macro (or something) that gets removed on release builds.

@vhakulinen How about something like this?
```rust
macro_rules! log {
    ($x:expr) => {
        #[cfg(debug_assertions)] // Debug builds.
        println!("{}", $x);
        #[cfg(not(debug_assertions))]
        // Put the output somewhere else on non-debug builds?
    };
}
```
Then just use `log!(format!("error message, {}", err));` instead of `println!("error message, {}", err);`. Definitely not perfect, but maybe a start?

**Comment by vhakulinen** [comment]
Something like that, yes. I would imagine that a macro like that would exists in the std library or as some official package.

**Comment by smolck** [comment]
Maybe this crate could work?
https://docs.rs/log/0.4.8/log/

**Comment by vhakulinen** [comment]
I think yes. That is owned by rust-lang-nursery (https://github.com/rust-lang-nursery/log).
