### ISSUE TITLE
Ability to set default size

### ISSUE THREAD

**Issue by clason** [vhakulinen/gnvim#108]
There currently doesn't seem to be a way to set the size of the gnvim window at startup; it always defaults to 1280x720. (Differently from neovim-qt, the window size also isn't saved and restored when closing and reopening.)

Or am I missing something?

**Comment by smolck** [comment]
Interesting. Probably not too difficult to fix if it’s an issue with GNvim, but I’m not sure if it is. Unfortunately, I can’t really test this with my setup, since I run SwayWM. Over here, GNvim gets the same default size as almost everything else! 😉

As an aside, thanks for opening these issues @clason 👏. Helps out with making GNvim better!

**Comment by clason** [comment]
What neovim-qt does is have an option `--geometry` that lets you override the default size, e.g., `neovim-qt --geometry 850x1400`. That would be perfectly sufficient for me (and should not be hard to implement?)

> As an aside, thanks for opening these issues @clason clap. Helps make GNvim better!

Oh, opening issues is easy. Thanks for actually putting in work!

**Comment by smolck** [comment]
> What neovim-qt does is have an option --geometry that lets you override the default size, e.g., neovim-qt --geometry 850x1400. That would be perfectly sufficient for me (and should not be hard to implement?)

I’ll have to look at Gtk-rs’s docs and such (for changing window size), but yeah, it probably wouldn’t be all that hard: just throw another cmdline arg in `main.rs` and change the window size if given one via that `geometry` arg.

> Oh, opening issues is easy. Thanks for actually putting in work!

No problem!

**Comment by clason** [comment]
> ’ll have to look at Gtk-rs’s docs and such (for changing window size), but yeah, it probably wouldn’t be all that hard: just throw another cmdline arg in main.rs and change the window size if given one via that geometry arg.

Currently the opening window size is hard-coded in https://github.com/vhakulinen/gnvim/blob/68e3fc8d2e8f6f7bbdd73641b00031c16004e8cc/src/ui/ui.rs#L113; it's probably sufficient to put the command line arguments here instead. (Parsing the argument seems the hardest part.)

**Comment by badosu** [comment]
One can define the options [here](https://github.com/vhakulinen/gnvim/blob/68e3fc8d2e8f6f7bbdd73641b00031c16004e8cc/src/main.rs#L64-L81) and pass the options [here](https://github.com/vhakulinen/gnvim/blob/68e3fc8d2e8f6f7bbdd73641b00031c16004e8cc/src/main.rs#L135).

**Comment by smolck** [comment]
I wonder what would happen if we removed the `window.set_default_size` call in ui.rs?

**Comment by clason** [comment]
@smolck You get a _very_ small window :)

**Comment by smolck** [comment]
> @smolck You get a _very_ small window :)

Makes sense!

@clason If you want to implement this fix yourself, feel free. I probably won’t get around to doing it ‘til later so there’s nothing stopping you from contributing if you want to.

**Comment by clason** [comment]
@smolck Done 

@badosu Thanks, that was very helpful!
