### ISSUE TITLE
Installing on OSX?

### ISSUE THREAD

**Issue by leeola** [vhakulinen/gnvim#110]
I'm having trouble installing gnvim on OSX due to the libwebkit2gtk requirement. How crucial is that to operating gnvim, and could a feature be added to opt out of that requirement?

**Comment by smolck** [comment]
@vhakulinen Isn’t libwebkit2gtk used to render markdown in the cursor tooltip?

**Comment by badosu** [comment]
Does Rust support optional dependencies?

**Comment by smolck** [comment]
> Does Rust support optional dependencies?
> 
> Edit: [Seems like it](https://github.com/rust-lang-nursery/edition-guide/issues/96). I think apart from the build process and feature handling adjustments, should be quite straightforward

Hopefully it can be done without too much boilerplate (e.g. `#cfg(...)` statements everywhere). Worst case scenario we could maybe make a separate, 'bare bones' branch of GNvim or something.

> BTW, I've never seen well formatted markdown on gnvim, when does it happen?

I believe it happens when hovering over something with gnvim-lsp installed; see bottom of [this page in the wiki](https://github.com/vhakulinen/gnvim/wiki) and [`cursor_tooltip.rs`](https://github.com/vhakulinen/gnvim/blob/master/src/ui/cursor_tooltip.rs).

**Comment by smolck** [comment]
@leeola Maybe https://github.com/vhakulinen/gnvim/issues/8#issuecomment-517421794 can help you?

**Comment by leeola** [comment]
I actually found that before posting _(during searching/etc)_, but didn't even try it due to it not working for the OP haha. Apparently it took over 2 hours, and still failed. I didn't bother heh.

**Comment by leeola** [comment]
Appreciate the discussion all. I should note that this issue is not widely important to me _(or I'd offer to help)_, so don't try too much on my account. I just wanted to give Gnvim a try, and thought I was missing something stupid. Thanks :)

**Comment by vhakulinen** [comment]
Adding the webkit2gtk dependency behind a (compile time) feature flag should be possible. PRs for this are welcome. Webkit is used to display markdown documents on the cursor tooltip.

Closing this as duplicate of #8.

**Comment by Lythenas** [comment]
I'm working on a PR for this. I haven't worked with rust for a while and this seems easy to do.

**Comment by kropper** [comment]
Yes, it builds now without error! :-)

However, after starting it, fonts are pretty messed up and the insert cursor cuts characters in half. Are there any settings recommended for running on macOS?

**Comment by vhakulinen** [comment]
Make sure you're using (and have available) a monospace font. Can you post a screenshot (or alternatively hop on the gnvim gitter channel)?
