### ISSUE TITLE
"Not supported option set: *"

### ISSUE THREAD

**Issue by skoenen** [vhakulinen/gnvim#114]
Neovim: 0.4.2
Linux: Archlinux
Gnvim: 0.1.5

Several messages indicating something is not correct:
```
ot supported option set: arabicshape
Not supported option set: ambiwidth
Not supported option set: emoji
Not supported option set: guifontset
Not supported option set: guifontwide
Not supported option set: pumblend
Not supported option set: showtabline
Not supported option set: termguicolors
Not supported option set: ext_linegrid
Not supported option set: ext_multigrid
Not supported option set: ext_hlstate
Not supported option set: ext_termcolors
Received unknown redraw event: hl_group_set
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_messages
Not supported option set: termguicolors
Received unknown redraw event: hl_group_set
Received unknown redraw event: update_menu
Not supported option set: showtabline
Received unknown redraw event: hl_group_set
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_messages
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_messages
Failed to turn input event into nvim key (keyval: 65507)
Failed to turn input event into nvim key (keyval: 32)
```
- Some key combinations like `Ctrl+Space` are not working.
- Modeline is off window.
- Tabline is not shown.

**Comment by vhakulinen** [comment]
`Not supported option set` messages are "expected", since not handling for those are not implemented. Related: #107 

Key combinations not working is an actual bug. Related #7 

For tabline, you need to actually open a tab, or disable ext-tabline (see `gnvim --help`).

**Comment by smolck** [comment]
@skoenen You shouldn’t be seeing the `Not supported option set` messages (without doing `RUST_log=gnvim=debug cargo run`) now that #122 is merged. Would you mind changing the issue title to focus on key combinations not working? Also, if you would like an option to keep the tabline shown at all times, you may wish to open another issue focusing on that.

**Comment by vhakulinen** [comment]
Right, after merging #122, the issue with noisy stdout should be gone. Closing. For other issues, please open new ticket(s).
