### ISSUE TITLE
Failed to subscribe to 'Gnvim' events

### ISSUE THREAD

**Issue by aneeshdurg** [vhakulinen/gnvim#115]
When I try to launch `gnvim` on ubuntu 18.04 (with the dependencies installed, rustc version 1.37-nightly) I get the following error (with backtrace)
```
thread 'main' panicked at 'Failed to subscribe to 'Gnvim' events: GenericError("Wait timeout (nvim_subscribe)")', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: rust_begin_unwind
             at src/libstd/panicking.rs:309
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
  11: gnvim::build
  12: <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline
  13: g_closure_invoke
  14: <unknown>
  15: g_signal_emit_valist
  16: g_signal_emit
  17: <unknown>
  18: g_application_run
  19: <O as gio::application::ApplicationExtManual>::run
  20: gnvim::main
  21: std::rt::lang_start::{{closure}}
  22: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  23: std::panicking::try::do_call
             at src/libstd/panicking.rs:294
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  25: std::panicking::try
             at src/libstd/panicking.rs:273
  26: std::panic::catch_unwind
             at src/libstd/panic.rs:388
  27: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  28: main
  29: __libc_start_main
  30: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fish: “env RUST_BACKTRACE=1 gnvim --nv…” terminated by signal SIGILL (Illegal instruction)
```

**Comment by aneeshdurg** [comment]
Doesn't compile with 1.37-stable, and I get the same error with 1.38-stable.

**Comment by smolck** [comment]
Could you provide a full backtrace with `RUST_BACKTRACE=full cargo run` (or just do that locally and link the line(s) where the panic happens)?

**Comment by smolck** [comment]
Also, what Neovim version are you using?

**Comment by barzilouik** [comment]
Same problem here, Ubuntu 18.04, NVIM v0.2.2, rustc 1.40.0-nightly (7979016af 2019-10-20), installed with the given make script.

`RUST_BACKTRACE=full gnvim
thread 'main' panicked at 'Failed to subscribe to 'Gnvim' events: GenericError("Wait timeout (nvim_subscribe)")', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x555f5b2ad9c4 - backtrace::backtrace::libunwind::trace::hc456a3386f914390
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x555f5b2ad9c4 - backtrace::backtrace::trace_unsynchronized::h4a2def0c1d55554e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x555f5b2ad9c4 - std::sys_common::backtrace::_print_fmt::hf14ed68b6789b5fe
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x555f5b2ad9c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6c47cffeeb327f7c
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x555f5b2d32dc - core::fmt::write::hc59b451f5f876e7f
                               at src/libcore/fmt/mod.rs:1028
   5:     0x555f5b2ab217 - std::io::Write::write_fmt::ha233981d002c27e5
                               at src/libstd/io/mod.rs:1412
   6:     0x555f5b2afefe - std::sys_common::backtrace::_print::hd01a0af84eb70ff6
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x555f5b2afefe - std::sys_common::backtrace::print::h53f5322cbc293596
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x555f5b2afefe - std::panicking::default_hook::{{closure}}::h0c7c40ba4f45458a
                               at src/libstd/panicking.rs:189
   9:     0x555f5b2afc01 - std::panicking::default_hook::h03ff9eee3bf4dec0
                               at src/libstd/panicking.rs:206
  10:     0x555f5b2b05f5 - std::panicking::rust_panic_with_hook::h07f06d6e0c8f4f10
                               at src/libstd/panicking.rs:469
  11:     0x555f5b2b0192 - std::panicking::continue_panic_fmt::h377975b493465ad6
                               at src/libstd/panicking.rs:376
  12:     0x555f5b2b0086 - rust_begin_unwind
                               at src/libstd/panicking.rs:303
  13:     0x555f5b2cf3da - core::panicking::panic_fmt::h1a1edca290ec60f6
                               at src/libcore/panicking.rs:84
  14:     0x555f5b2cf4d7 - core::result::unwrap_failed::h4ea71a0fe947d4a8
                               at src/libcore/result.rs:1165
  15:     0x555f5b0a7b60 - gnvim::build::h34036ee5cc73c2e7
  16:     0x555f5b0fdded - <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline::h4dc7d15be3775b27
  17:     0x7f448003c10d - g_closure_invoke
  18:     0x7f448004f05e - <unknown>
  19:     0x7f4480057715 - g_signal_emit_valist
  20:     0x7f448005812f - g_signal_emit
  21:     0x7f44815a3b95 - <unknown>
  22:     0x7f44815a3da6 - g_application_run
  23:     0x555f5b114c94 - <O as gio::application::ApplicationExtManual>::run::ha65aff8a4c039ed9
  24:     0x555f5b0a8fac - gnvim::main::h86903bc89bbf6ee0
  25:     0x555f5b0a99d3 - std::rt::lang_start::{{closure}}::h05516cf2a2a0df5a
  26:     0x555f5b2b0023 - std::rt::lang_start_internal::{{closure}}::h60689213005b9925
                               at src/libstd/rt.rs:48
  27:     0x555f5b2b0023 - std::panicking::try::do_call::h05c9df1269da0aaf
                               at src/libstd/panicking.rs:288
  28:     0x555f5b2b6e1a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  29:     0x555f5b2b0aed - std::panicking::try::hafbf0fba589aaf5d
                               at src/libstd/panicking.rs:267
  30:     0x555f5b2b0aed - std::panic::catch_unwind::h7ccaae070d313a9c
                               at src/libstd/panic.rs:396
  31:     0x555f5b2b0aed - std::rt::lang_start_internal::h4288df0c8eeb61c6
                               at src/libstd/rt.rs:47
  32:     0x555f5b0a93c2 - main
  33:     0x7f447f102b97 - __libc_start_main
  34:     0x555f5b08868a - _start
  35:                0x0 - <unknown>
`

**Comment by smolck** [comment]
@barzilouik GNvim requires latest nvim master, or at the very least nvim v0.3.4. From README here: https://github.com/vhakulinen/gnvim#features

> GNvim requires . . . Latest nvim master (gnvim 0.1.0 works with nvim 0.3.4)

Could you try updating Neovim to the [latest master](https://github.com/neovim/neovim/releases/tag/v0.4.2) and see if the issue persists?

**Comment by smolck** [comment]
Alternatively, you can download the latest master from https://github.com/neovim/neovim/releases/tag/v0.4.2 and then run GNvim like this:
```console
$ gnvim --nvim path/to/nvim/binary
```

**Comment by vhakulinen** [comment]
Try with the latest nvim release (I updated that as a requirement to the readme too).

**Comment by aneeshdurg** [comment]
Yup, running with the latest nvim fixes it, thanks!
