### ISSUE TITLE
Detect gnvim in vimrc

### ISSUE THREAD

**Issue by TyberiusPrime** [vhakulinen/gnvim#116]
Hello,

I have a line in my config, 'set title', that apparently crashes gnvim during startup.
But that's a separate bug.
For now, all I want is to not run that line when gnvim is reading my init.vim

Unfortunately ```!has('gui_running')``` doesn't seem to work.

How do I do this?

**Comment by smolck** [comment]
```viml
if exists(‘g:gnvim’)
       “ Do stuff here
endif
```

Could you also post an issue on the `set title` bug?

**Comment by TyberiusPrime** [comment]
Thanks!

**Comment by smolck** [comment]
No problem! Of course, you’ll want to do `if !exists(‘g:gnvim’)`. I skimmed your question and missed that ;)

**Comment by smolck** [comment]
@vhakulinen I think we may want to add this sort of information to the README in some way. Maybe an example `init.vim` with helpful comments?

**Comment by vhakulinen** [comment]
That could be added to the github wiki.
