### ISSUE TITLE
Initial font rendering is variable-width

### ISSUE THREAD

**Issue by hasufell** [vhakulinen/gnvim#118]
Starting gnvim I get:

![gui_font](https://user-images.githubusercontent.com/1241845/67353354-f36ce900-f584-11e9-9121-e97ea2db3c3a.png)

Font is "Monospace 14".

After typing `:set guifont=Monospace 14` it works. Never had this issue in gvim, neovim-gtk or any other vim-like editor.

I don't know if this is related to https://github.com/vhakulinen/gnvim/issues/84

**Comment by smolck** [comment]
What are your Neovim, GNvim, and pango (see #85) versions? Also, could you point out exactly where the issues are occurring in that image? I’m not quite sure what part(s) of it you’re referring to.

**Comment by hasufell** [comment]
> What are your Neovim

From git master

> GNvim

From git master

> pango

1.42.4

> I’m not quite sure what part(s) of it you’re referring to.

The lines do not align, there should be no space between the dots, some characters overlap...

Here is a screenshot with the correct font:

![correct_gui](https://user-images.githubusercontent.com/1241845/67356603-45197180-f58d-11e9-8ef3-85e7af874b47.png)

**Comment by smolck** [comment]
Thank you! This could be related to #84, but I’m not sure. Could you try any of the workarounds listed in these comments?
https://github.com/vhakulinen/gnvim/issues/84#issuecomment-520845180 and https://github.com/vhakulinen/gnvim/issues/84#issuecomment-520886920

**Comment by hasufell** [comment]
@smolck well, as I said, a trivial `:set guifont=Monospace 14` fixes it, but it doesn't make any sense

**Comment by vhakulinen** [comment]
The syntax is `Monospace:h14`.

**Comment by hasufell** [comment]
I don't think so, because setting it explicitly as "Monospace 14" works. Just on application startup it is messed up. The syntax also works on gvim.

**Comment by vhakulinen** [comment]
But if you set `Monospace:h14` in `init.vim`, does it work?
