### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by fitojb** [vhakulinen/gnvim#119]
This application’s <s>GUI</s>UI doesn’t seem to be translatable yet :)

**Comment by smolck** [comment]
Like to other editor backends, such as Kakoune or Xi-editor? That is outside the scope of _this_ project, but I might fork it and see what I can do in that department. ATM GNvim is fairly intertwined with Neovim, so I’m not sure how feasible such a project is. But I just might give it a shot :)

**Comment by vhakulinen** [comment]
> This application’s GUI doesn’t seem to be translatable yet

You mean actually translatable from a one language to another? There isn't anything to translate really, except the cli interface (e.g. the `--help` doc). Other than that, everything is coming from neovim.

**Comment by fitojb** [comment]
Yeah, I figured since there are definitions for the keyboard shortcuts and CLI strings, there’d be some mixed-language strings for users to see :)

**Comment by vhakulinen** [comment]
There seems to be an open issue in clap's issue tracker (a library we use to build the cli interface): https://github.com/clap-rs/clap/issues/380. I think we're stuck on that for time being.

For future reference, the actual GUI (if it ever is going to get content thats not from neovim) should be possible to be translated using gtk/gnome tools.
