### ISSUE TITLE
crash when used with gnvim-lsp

### ISSUE THREAD

**Issue by teto** [vhakulinen/gnvim#12]
I've packaged gnvim for nixos (at least on my computer):

When I add 
`Plug 'vhakulinen/gnvim-lsp' " load it only for gnvim`
and start gnvim 0.1.1 I get

```
Not supported option set: arabicshape
Not supported option set: ambiwidth
Not supported option set: emoji
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GenericError("Wait timeout (nvim_ui_try_resize)")', src/libcore/result.rs:1009:5

```
with a neovim with floating windows
```
      src = builtins.fetchGit {
        url = https://github.com/neovim/neovim.git;
        ref = "+refs/pull/6619/head";
      };

```
akin to
```
:version
NVIM v0.4.0-dev                                                                                                              
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compilé par nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/nix/store/w177ksf3nz8gvw7bijbrc6bgzwmbi643-neovim/share/nvim"
```
Is my nvim too new or shoudl it be handled already ?
Might be related: https://github.com/vhakulinen/gnvim/issues/10

**Comment by vhakulinen** [comment]
Does it work properly with gnvim 0.3.4?

**Comment by vhakulinen** [comment]
Oh, do you have `vim-lsp` plugin installed? Its required by gnvim-lsp, but there are no checks for its existence. Missing `vim-lsp` might result in errors when sourcing gnvim-lsp files which would result in errors and problems described in #10 will take effect.

**Comment by teto** [comment]
this vim-lsp  https://github.com/prabirshrestha/vim-lsp ? or the one from bfredl ? with the first one it still crashes.

**Comment by vhakulinen** [comment]
Can you try now with the latest master?

**Comment by teto** [comment]
yes. Doesn't crash anymore.
