### ISSUE TITLE
I/O error while reading marker byte

### ISSUE THREAD

**Issue by BenjaminJames19041999** [vhakulinen/gnvim#129]
I got the error while launching gnvim from my terminal 
`[2020-05-29T14:08:14Z ERROR neovim_lib::rpc::client] Error while reading: I/O error while reading marker byte: failed to fill whole buffer`
Help me, how to fix it.

**Comment by vhakulinen** [comment]
Which neovim version are you using?

**Comment by vhakulinen** [comment]
Closing because not getting any input.
