### ISSUE TITLE
Background transparency

### ISSUE THREAD

**Issue by Danoloan10** [vhakulinen/gnvim#130]
It could be nice to support a background with transparency, for those who come from terminals with transparent backgrounds.

**Comment by smolck** [comment]
Hello! Thanks for opening this issue!

So, I think this shouldn't be that hard to implement, just maybe a bit tedious. First thing to be done is probably to refactor this struct to contain an `a` value:

https://github.com/vhakulinen/gnvim/blob/13bd8b0590f43881661ca02cb81bf6a5e65e02eb/src/ui/color.rs#L59-L63

I'll have to look into what exact changes will need to take place after that, but as I said I don't think it will be that difficult.

**Comment by matheusfillipe** [comment]
Would be nice indeed. Is someone working on this? (I could try myself but I am kind of a rust newbie)

**Comment by vhakulinen** [comment]
Nobody's working on it. There probably is a way [gtk way](https://stackoverflow.com/questions/3908565/how-to-make-gtk-window-background-transparent) to do it.

**Comment by vhakulinen** [comment]
I'm not currently planning to add this feature.
