### ISSUE TITLE
Webdevicons + Gnvim

### ISSUE THREAD

**Issue by Aletz-Arce** [vhakulinen/gnvim#133]
Hi,
I'm in a weird problem, vim-webdevicons is not showed in Gnvim but in kitty + nvim yes.

![kitty-nvim](https://user-images.githubusercontent.com/5661038/85804483-5c59c180-b70f-11ea-926e-2c6107578159.png)

![gnvim](https://user-images.githubusercontent.com/5661038/85804420-2e747d00-b70f-11ea-969e-9e186d895a35.png)

Anyone tried use vim-webdevicons with nvim?
Thanks

**Comment by smolck** [comment]
Is the font the same (a NERD font) in both kitty & gnvim? If not, you should be able to set GNvim's font by using `:set guifont=<...>` (see `:help guifont`) to a NERD font and see if that fixes the problem.

**Comment by Aletz-Arce** [comment]
> Is the font the same (a NERD font) in both kitty & gnvim? If not, you should be able to set GNvim's font by using `:set guifont=<...>` (see `:help guifont`) to a NERD font and see if that fixes the problem.

Yes it's the same font, in my current vimrc setup i have line
`
set guifont=Source\ Code\ Pro\ for\ Powerline:h12
`

**Comment by Aletz-Arce** [comment]
Ok, you are right @smolck  i'm use incorrect font,
switching to Fira Code Nerd Font, all look right.
Thanks

**Comment by smolck** [comment]
@Aletz-Arce No problem! So this issue can be closed then?

**Comment by Aletz-Arce** [comment]
> @Aletz-Arce No problem! So this issue can be closed then?

Yes, thanks!
