### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by vhakulinen** [vhakulinen/gnvim#135]
At the moment, gnvim doesn't run on windows (anymore). This is because I moved the neovim's subprocess to use GTKs subprocess instead of rust's std `Command`, so that we do the IO in GTK's main loop and not in separate IO thread and thus avoid some deadlocks.

The problem lies with GTK's stdin/stdout pipes - on windows there is no pollable interface implemented for them (see: https://gitlab.gnome.org/GNOME/glib/-/issues/2016). There are couple of ways to fix this:
* Help with the above glib issue and implement the needed interface
* Incorporate [Wing](https://gitlab.gnome.org/GNOME/wing/-/tree/master) into gnvim (requires FFI crate for said library). This library was mentioned in the glib issue
* Spawn an IO thread with the current implementation when running on windows

Meawhile, if you want to run gnvim on windows, you can use this commit: https://github.com/vhakulinen/gnvim/commit/5339bb566281d21b4f73a68fb54ef2113c77e27e.

**Comment by FelipeLema** [comment]
do mind that webkit2gtk-4.0 is not being supported in windows for more than a year (see https://github.com/msys2/MINGW-packages/issues/3484#issuecomment-483427316 )
