### ISSUE TITLE
Failed to build UI

### ISSUE THREAD

**Issue by law27** [vhakulinen/gnvim#136]
When I tried to open gnvim via terminal I am getting this following error
`ERROR gnvim] Failed to build UI: Call to nvim failed: Error processing request: 1 - 'No such ui option')`

**Comment by vhakulinen** [comment]
Which nvim version are you using?

**Comment by law27** [comment]
gnvim v0.1.6-25-g0ac2cef

**Comment by vhakulinen** [comment]
Thats gnvim version. Whats your neovim version? (e.g. `nvim --version`).

**Comment by law27** [comment]
I am sorry!
Nvim version is `NVIM v0.2.2`

**Comment by vhakulinen** [comment]
You need newer version of nvim, either latest release or latest mater. I recommend latest master because it has some bugs fixed related to `ext_multigrid`.
