### ISSUE TITLE
CTRL-^ (Edit the alternate file.) not working

### ISSUE THREAD

**Issue by afreakk** [vhakulinen/gnvim#137]
Hi, 
Is there a reason CTRL-^ hotkey is not working?
`gnvim 0.1.6`
`NVIM v0.4.3`

**Comment by vhakulinen** [comment]
Works for me. Does nvim echo any messages when you press `CTRL-^`. What keyboard layout are you using?

**Comment by afreakk** [comment]
im using US layout, not sure what you mean by echo.
it works without any messages or errors when i run it from nvim inside a terminal, but not in gnvim (no errors as far as i can see there either).

**Comment by vhakulinen** [comment]
Should be fixed now in the master branch. Can you give it a try?

**Comment by afreakk** [comment]
Yeah, it works now.
Thanks!
