### ISSUE TITLE
Toggling cursor blink keeps current transparency level

### ISSUE THREAD

**Issue by agraven** [vhakulinen/gnvim#138]
When toggling between a blinking and non-blink cursor for example by running `set guicursor+=a:blinkon1000,i:blinkon0` and toggling between insert mode and normal mode, the cursor keeps its current level of transparency when blinking is disabled. This means that when you disable blinking while the cursor is entirely transparent, i.e. invisible, the cursor stays invisible. This is kind of inconvenient when you prefer to have different blinking rules for different modes like I do.

I'm running the latest master (`bfc7629`).

**Comment by vhakulinen** [comment]
Fixed.
