### ISSUE TITLE
Fails to start on Gnome Wayland

### ISSUE THREAD

**Issue by Caduser2020** [vhakulinen/gnvim#139]
OS: Archlinux GNOME using Wayland.

Attempting to launch gnvim results in the error
```
gnvim: ../egl-wayland/src/wayland-thread.c:87: wlExternalApiLock: Assertion `!"failed to lock pthread mutex"' failed.
[1]    23804 abort (core dumped)  GDK_BACKEND=wayland gnvim
```

I confirmed it works with GDT_BACKEND=x11, however I would prefer native Wayland support.

**Comment by vocasle** [comment]
Hi, @Caduser2020 
I am using GNvim on Arch Linux with Gnome on Wayland and it works well.

GNvim version: gnvim v0.1.6-49-g1a47380
GDM version: 3.36.3
Kernel version: 5.7.12-arch1-1

**Comment by Caduser2020** [comment]
Nevermind, this was because of https://github.com/NVIDIA/egl-wayland/issues/27, which is fixed now.
