### ISSUE TITLE
Wrong version number in tarball

### ISSUE THREAD

**Issue by Hawk777** [vhakulinen/gnvim#140]
I went to the Releases page on Github and downloaded the latest release tarball (0.1.6). After extracting it, in `Cargo.toml`, the `version` field is set to 0.1.0.

**Comment by vhakulinen** [comment]
Gnvim doesn't use the version in `Cargo.toml`. Our build script extracts the version number from git tags (on build).

**Comment by Hawk777** [comment]
> git tags

Which don’t exist if you download a tarball. But feel free to close this ticket if you don’t consider the tarballs on your Releases page to be an acceptable way to get package sources.

**Comment by vhakulinen** [comment]
This current way has proven to be a problem with others too, so I'll probably adjust my release flow to add the version number into the `Cargo.toml` file.

**Comment by vhakulinen** [comment]
Gnvim was rewritten from ground up for gtk4, and the current build file doesn't try access git anymore for the version number. If the problem persists, feel free to reopen this issue.
