### ISSUE TITLE
Gui cursor don't show

### ISSUE THREAD

**Issue by phaalonso** [vhakulinen/gnvim#141]
Hi, I'm just installed gnvim and my cursor isn't showing. How do I fix this?
Where my cursor is:
![image](https://user-images.githubusercontent.com/26033899/89066178-66409700-d343-11ea-9f71-2e15c437cb44.png)

What is showing:
![image](https://user-images.githubusercontent.com/26033899/89066240-840dfc00-d343-11ea-9b07-1270fc882aba.png)

**Comment by vhakulinen** [comment]
What your `guicursor`? Can you try with `set guicursor+=a:blinkon333`?

**Comment by phaalonso** [comment]
Its works, I tried to set the configuration yesterday but it doesn't change anything. Now it changed :thinking:
Today I have using Nvidia and changed to Intel in Nvidia prime. This can affect gnvim?

![image](https://user-images.githubusercontent.com/26033899/89102639-b53d0980-d3e1-11ea-9637-879c76813d2f.png)

**Comment by phaalonso** [comment]
How I do this fix in splits? When moving to a split the cursor disappears again ;(

**Comment by phaalonso** [comment]
Hmm. I noticied that every time that gnvim opened the cursor isn't showing up and I have to run

```
set guicursor+=a:blinkon333
set guicursor=
```
So that the cursor showed up, and return it to the normal configuration. But this doesn't seem to be working when using directly in coc.vim config

**Comment by augustobmoura** [comment]
Same with me

**Comment by vhakulinen** [comment]
Fixed.
