### ISSUE TITLE
Doesn't seem to respect GTK_THEME environment variable

### ISSUE THREAD

**Issue by jacobmischka** [vhakulinen/gnvim#142]
I'd love it if I could change gnvim's window border using `GTK_THEME=Adwaita:dark gnvim`, but this doesn't seem to have any effect.

From the [Running GTK+ Applications page](https://developer.gnome.org/gtk3/stable/gtk-running.html):

> `GTK_THEME`.  If set, makes GTK+ use the named theme instead of the theme that is specified by the gtk-theme-name setting. This is intended mainly for easy debugging of theme issues. It is also possible to specify a theme variant to load, by appending the variant name with a colon, like this: `GTK_THEME=Adwaita:dark`. 

Thanks for the great app!

**Comment by vhakulinen** [comment]
Fixed in https://github.com/vhakulinen/gnvim/commit/336edb667b4235b5b7bbbf39de166c6a2e3fd0ce
