### ISSUE TITLE
fzf window layout is empty

### ISSUE THREAD

**Issue by jtumano** [vhakulinen/gnvim#144]
Hi! First of all thanks a lot for a great nvim gui. 

There is an issue when using fzf window layout:
config option is for example: 
```
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
```

resulted with an empty floating window:
![image](https://user-images.githubusercontent.com/14204232/89531250-98953d00-d7f8-11ea-841a-d3f9286a1866.png)

in terminal nvim it should look as 
![image](https://user-images.githubusercontent.com/14204232/89531381-d2664380-d7f8-11ea-99c7-476516f5d892.png)

after some tries I found that if I click on this empty window and "close" it by pressing Ctrl+W c then content will be shown, but without a border:
![image](https://user-images.githubusercontent.com/14204232/89531542-12c5c180-d7f9-11ea-8cef-1ad31115170a.png)

**Comment by vhakulinen** [comment]
This is probably because fzf is creating a base window for a "frame" for the actual window that shows the contents (see https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L909-L914). The "actual" window should specify the frame as a anchor window.

**Comment by vhakulinen** [comment]
Also, even if the anchor is specified, gnvim currently doesn't make sure that the stacking order of the windows is correct - so there is a bug in both fzf and gnvim.

**Comment by vhakulinen** [comment]
Meanwhile, FWIW, I'm using this for fzf layout:

```viml
let $FZF_DEFAULT_OPTS=' --layout=reverse --margin=1,4'
let g:fzf_layout = { 'window': 'call FloatingFZF()' }

function! FloatingFZF()
  let buf = nvim_create_buf(v:false, v:true)
  call setbufvar(buf, '&signcolumn', 'no')

  let height = 20
  let width = 120
  let horizontal = float2nr((&columns - width) / 2)
  let vertical = 1

  let opts = {
        \ 'relative': 'editor',
        \ 'row': vertical,
        \ 'col': horizontal,
        \ 'width': width,
        \ 'height': height,
        \ 'style': 'minimal'
        \ }

  call nvim_open_win(buf, v:true, opts)
endfunction

```

**Comment by vhakulinen** [comment]
Gnvim was rewritten from ground up for gtk4. If the problem persists, feel free to reopen this issue.
