### ISSUE TITLE
Option to turn off ligatures

### ISSUE THREAD

**Issue by sasq64** [vhakulinen/gnvim#148]
I use the _Jetbrains_ font (which incidentally has ligatures) that I really would like to turn off.

**Comment by TheExistingOne** [comment]
I really think gnvim should support this. NerdFonts patched fonts have this problem where fi and fl try to become symbols and the only real way to fix it is disabling ligatures. Not using NF also isn't really an option because it's necessary for nerdtree icons

**Comment by vhakulinen** [comment]
As far as I know, pango (which is used for font rendering inside gnvim) doesn't have API to disable ligatures. You can either try to adjust your [system settings](https://wiki.archlinux.org/title/Font_configuration/Examples#Disable_ligatures_for_monospaced_fonts) or use a font that doesn't have ligatures.
