### ISSUE TITLE
Cursor falling behind when scrolling

### ISSUE THREAD

**Issue by danielakhterov** [vhakulinen/gnvim#150]
Not exactly sure if my eyes are deceiving me, but it seems that the block cursor is falling behind when scrolling up and down. I have `cursorline` set, and from what I can tell the line and the block cursor are being split apart.

gnvim version: `gnvim v0.1.6-55-g284c373`
nvim version: ```NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info```

Edit: Experimenting a little more it seems that when scrolling horizontally it seems that each character is being redrawn with the highlighted background, and since the cursor bar is animated when moving the the character also seems to move. When selecting a region the font size seems to change. From the following image you can see the second closing curly brace is smaller than the first.
![image](https://user-images.githubusercontent.com/36461294/91362866-35237d00-e7b0-11ea-8de6-fd100383f177.png)

**Comment by vhakulinen** [comment]
Gnvim was rewritten from ground up for gtk4. If the problem persists, feel free to reopen this issue.
