### ISSUE TITLE
Overlapping Suggestions

### ISSUE THREAD

**Issue by Avineak** [vhakulinen/gnvim#151]
The word completion suggestions and the description of the suggestion overlaps making it hard to see whats behind it.
![bug](https://user-images.githubusercontent.com/43460240/92298323-6d248000-ef67-11ea-9be2-dde446fd0977.png)

**Comment by vhakulinen** [comment]
I'm sorry, I don't quite understand. Whats happening here, and whats the problem?

**Comment by phaalonso** [comment]
I think its the same problem that #146

**Comment by Avineak** [comment]
Thank you "--disable-ext-popupmenu" seems to solve the problem.
