### ISSUE TITLE
Strange look on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by dnezamaev** [vhakulinen/gnvim#154]
Installed everything according README (rust tool chain, libgtk-3-dev libwebkit2gtk-4.0-dev, make, install) but there so many graphics flaws. Please tell me what am I doing wrong? Ubuntu 20.04 LTS, last updates, last nvim, last rust on this week.

![Screenshot from 2020-10-07 20-31-58](https://user-images.githubusercontent.com/1729333/95367412-67f77f80-08dd-11eb-8f89-3869ded047ce.png)

And here how GVim looks with same config.

![Screenshot from 2020-10-07 20-32-51](https://user-images.githubusercontent.com/1729333/95367470-7cd41300-08dd-11eb-82aa-4857e9884a40.png)

**Comment by caerphoto** [comment]
I'm facing the same issue and it seems it's because gnvim doesn't source my ginit.vim ? If I manually set the options in ginit.vim they work as expected.

**Comment by vhakulinen** [comment]
Gnvim doesn't source ginit.vim. Gnvim sets `g:gnvim` value which you can use to guard your gnvim specific options: https://github.com/vhakulinen/gnvim/issues/116#issuecomment-544961162.

For OG problem, it looks like you're using variable width font and not a monospace font. Try `:set guifont=Monospace:h13` or your preferred (monospace) font.
