### ISSUE TITLE
has('gui_running') not working

### ISSUE THREAD

**Issue by kernel-panic96** [vhakulinen/gnvim#156]
Hello, love the look of the editor. I'm in a period where I use both nvim and gnvim and I cannot find a way to config it in my .vimrc, the if guard of has('gui_running') does not work. Also the suggestion in `:h gvim` to 
to autocmd based on the UIEnter event, for some reason gets sourced in nvim and the gnvim commands error out because they don't exist in plain nvim. Is there a preferred way to config the editor and if not can you provide one, please?

**Comment by vhakulinen** [comment]
Gnvim sets `g:gnvim` which can be used as a guard for gnvim configuration in your init.vim (ref: https://github.com/vhakulinen/gnvim/issues/116#issuecomment-544961162).
