### ISSUE TITLE
Copy paste in command mode not working

### ISSUE THREAD

**Issue by kernel-panic96** [vhakulinen/gnvim#157]
I'm unable to paste with C-v or C-V, mainly in command mode but other modes too, e.g. insert. I'm running linux, ubuntu 20.04 currently.  The normal mode copy & paste works when I `set clipboard=unnamedplus`

**Comment by vhakulinen** [comment]
What ever works on nvim should work just fine in gnvim (e.g. the normal commands to yank and paste).

**Comment by kernel-panic96** [comment]
Copy and paste is handled by the terminal emulator

**Comment by vhakulinen** [comment]
See `:h clipboard` and maybe check this out: https://vi.stackexchange.com/questions/84/how-can-i-copy-text-to-the-system-clipboard-from-vim

**Comment by kernel-panic96** [comment]
I am able to paste with `<C-R>+` in command mode. Ideally I would like C-V to work but since there is a way, I'm fine if you wish to close the issue.

**Comment by vhakulinen** [comment]
You can map that with `:cnoremap <c-v> <c-r>+`.
