### ISSUE TITLE
`cargo build` doesn't work from release tarball: "Failed to get version from git"

### ISSUE THREAD

**Issue by orip** [vhakulinen/gnvim#159]
Using the https://github.com/vhakulinen/gnvim/archive/v0.1.6.tar.gz release tarball and following the instructions to build on Mac (same result with calling `cargo build` directly):
```
$ brew install gtk+3 librsvg
$ make NOWEBKIT2GTK=1
```

I get this error:
```
error: failed to run custom build command for `gnvim v0.1.0 (/tmp/gnvim-0.1.6)`

Caused by:
  process didn't exit successfully: `/tmp/gnvim-0.1.6/target/release/build/gnvim-2cad858175235b2e/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Failed to get version from git', build.rs:18:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Being able to build from the source tarball is, of course, desirable.

**Comment by vhakulinen** [comment]
Gnvim was rewritten from ground up for gtk4, ant the build file doesn't try to access git anymore. If the problem persists, feel free to reopen this issue.
