### ISSUE TITLE
Setting GnvimCursorEnableAnimations in vimrc doesn't work

### ISSUE THREAD

**Issue by dead10ck** [vhakulinen/gnvim#162]
I'd like to permanently disable the cursor animations, but it looks like when I put the `GnvimCursorEnableAnimations 0` in my vimrc, it fails with an error that says `Not an editor command: GnvimCursorEnableAnimations 0`

**Comment by mulianov** [comment]
Could you please add command line option for this?

**Comment by MeanEYE** [comment]
Another issue I have with this approach is that there's no way to detect if GUI is running and just blindly calling rpcnotify it not working for CLI version.

**Comment by vhakulinen** [comment]
You can check if gnvim is running with `exists("g:gnvim")`

**Comment by MeanEYE** [comment]
> You can check if gnvim is running with `exists("g:gnvim")`

Thanks. I managed in different way. I'll change this code. Is there a reason why `ginit.vim` and `gvimrc` are not executed? Until now that's where people kept their GUI configs.

**Comment by vhakulinen** [comment]
No other reason than just to not have it. You can source it manually if you so desire (see `:h source`).

**Comment by MeanEYE** [comment]
I know I can source it, but whole point of it existing was that we didn't have to do GUI detection on our own, just put GUI specific stuff there. Pretty much every iteration of Vim does it. I don't have many commands explicitly for GUI so it's not an issue for me, but might be for others.

**Comment by vhakulinen** [comment]
The GUI specific stuff you might want to do likely depends on the GUI you're using, so you'd need to do that detection within `ginit.vim` either way.

**Comment by vhakulinen** [comment]
Gnvim was rewritten from ground up for gtk4. If the problem persists, feel free to reopen this issue.
