### ISSUE TITLE
Incorrect offsets with multiple panes

### ISSUE THREAD

**Issue by rosskidson** [vhakulinen/gnvim#165]
When multiple panes open and the mouse is used to click and select text for a visual mode selection, the selection is offset by the width of the first pane. See screenshot.

![vselect_offset](https://user-images.githubusercontent.com/2621519/103885045-bb958700-50df-11eb-9321-8d1fda11d07c.png)
The mouse left button is depressed at the time of screenshot.

The same problem happens for horizontal panes, the mouse needs to be moved further down in order to select text.  In my vimrc I have `set mouse=a`

In the screenshot above it is also apparent that the hover box window position is also incorrect.  The drawing coordinates seem to be with respect to the window instead of the pane.

**Comment by vhakulinen** [comment]
This is because of a bug in neovim. PR to fix it is here: https://github.com/neovim/neovim/pull/12667

**Comment by rosskidson** [comment]
Thanks for the quick reply!

I tried your bugfix branch, and it did indeed fix the text selecting problem, thank you.  However the hover box still remained in the incorrect location.  That is, when I have multiple vertical panes, and I hover over an element in the far right pane, the hover popup appears on the left.

Should I perhaps open a separate issue to decouple these two problems?  And is this maybe an issue with the `gnvim-lsp` plugin rather than gnvim itself?
