### ISSUE TITLE
How to get correct v:windowid?

### ISSUE THREAD

**Issue by newptcai** [vhakulinen/gnvim#168]
In my vimrc, I have the following line
```
autocmd GuiEnter * silent! call system('wmctrl -i -b add,maximized_vert,maximized_horz -r '.v:windowid)
```
This automatically maximizes gvim window on startup. But this does not work for `gnvim`, because `v:windowid` is 0 in gnvim. So is there a way to get the actual windowid?

**Comment by vhakulinen** [comment]
Gnvim doesn't currently report any window handles to nvim.
