### ISSUE TITLE
Gnvim ignores cursor color settings (highlight group Cursor) 

### ISSUE THREAD

**Issue by mulianov** [vhakulinen/gnvim#170]
Changing Hl Cursor  doesn't do any changes

**Comment by vhakulinen** [comment]
The `:h ui` documents in the `mode_info_set` event[1]:
> 	`attr_id`:	Cursor attribute id (defined by `hl_attr_define`).
>			When attr_id is 0, the background and foreground
>			colors should be swapped.

I interpret that as to "use this hl id for the cursor's color". @bfredl is the `Cursor` hl ignored by the `mode_info_set` event?

1: https://github.com/neovim/neovim/blob/d311c5481dede47d752fa39cb00d728ba18ef5bc/runtime/doc/ui.txt#L188-L190

**Comment by vhakulinen** [comment]
Working as intended. You need to define the used highlight group for the cursor in `guicursor`.
