### ISSUE TITLE
Incorrect cursor shape?

### ISSUE THREAD

**Issue by Barbaross93** [vhakulinen/gnvim#172]
In both the latest git and release versions of GNvim, I've noticed that the cursor shape always remained as a ibeam. In my init.vim, it should be a horizontal bar. When I try to apply the setting, I can see that the cursor thickness changes if I try something like `set guicursor=a:hor10` or `set guicursor=a:hor20` but the shape itself does not change.

**Comment by vhakulinen** [comment]
Note to self: the cursor currently doesn't consider the shape. See https://github.com/vhakulinen/gnvim/blob/8f020b26f86168f9855489293e6ad725c2a4b45b/ui/src/components/cursor/imp.rs#L160-L185
