### ISSUE TITLE
Double click for selecting word, triple click for selecting line

### ISSUE THREAD

**Issue by codic12** [vhakulinen/gnvim#174]
Currently double clicking in gnvim selects the full line. The usual behavior in most applications is double click selects a word and triple click selects the full line. It would be great if this were implemented, I'll dive into the code to see if I can submit a PR.

**Comment by 01mf02** [comment]
I would also appreciate this behaviour.

**Comment by vhakulinen** [comment]
Gnvim passes mouse input to neovim, so the behavior you're seeing is coming from neovim.
