### ISSUE TITLE
Allow changing the GTK class name using `--class`

### ISSUE THREAD

**Issue by bergercookie** [vhakulinen/gnvim#179]
Hi there,

Many GUI programs allow you to change the WM_CLASS of this program using a `--class` argument, e.g., see `gnome-terminal`.
This would be useful e.g., in `i3` for assigning specific programs to specific workspaces and having a fine-grained control over this.

Thanks for this awesome project
Nikos

**Comment by bergercookie** [comment]
Hi @vhakulinen, friendly ping :)

**Comment by vhakulinen** [comment]
Afaik gtk4 removed builtin support for doing this, and I'm not planning to support this myself (I've no personal use for it nor desire/motivation to do the work).
