### ISSUE TITLE
UTF Box Drawing Characters

### ISSUE THREAD

**Issue by ceuk** [vhakulinen/gnvim#188]
Hey, if i create a floating window with the following border chars:

```
 ['🭽', '▔', '🭾', '▕', '🭿', '▁', '🭼', '▏']
```

It doesn't render very nicely:

![image](https://user-images.githubusercontent.com/1681236/147675795-1309c773-89d3-4783-829a-b77f67a5a670.png)

(looks fine in various terminal emulators)

**Comment by vhakulinen** [comment]
Gnvim was rewritten from ground up for gtk4. This also changed how the grid is rendered. If the problem persists, feel free to reopen this issue.
