### ISSUE TITLE
gvimrc not loaded

### ISSUE THREAD

**Issue by oHaiyang** [vhakulinen/gnvim#19]
I use gnvim on Arch Linux, but my gvimrc file seems not be loaded after gnvim starts.

vimrc location: `~/.config/nvim/init.vim`
gvimrc location: `~/.config/nvim/ginit.vim`

BTW, the vimrc works fine

**Comment by vhakulinen** [comment]
gnvim doesn't load `ginit.vim`. In `init.vim`, you can detect if gnvim is present by using `exists("g:gnvim")`. You can load `ginit.vim` by using that.

**Comment by noboruma** [comment]
@vhakulinen would it be possible to make has("gui_running") returning true as well? (This is what gvim does)

**Comment by vhakulinen** [comment]
I don't think neovim supports that.
