### ISSUE TITLE
Darker color within terminal inside gnvim

### ISSUE THREAD

**Issue by tuanbass** [vhakulinen/gnvim#191]
![image](https://user-images.githubusercontent.com/9334023/174275165-81074a3e-3fda-4b53-98cb-173ca34dacc0.png)

Hi, 

When I open terminal inside  gnvim, the color is very strange. 
Left is original color(open terminal directly using alacritty. Right is open inside gnvim. Text in gnvim is much darker, and sometime I cannot read it. 

I'm using Ubuntu 22.04, but the problem occurs also in 20.04 
- gnvim v0.1.6-88-g6ba4737
- No vimrc/init.lua config at all (problem also occurs when loading my init.lua)
- change other colorscheme has no effect

Any idea ? 
Thanks

**Comment by vhakulinen** [comment]
gnvim uses what ever colors neovim tells it to. You'll have to fiddle with your colorscheme.

FWIW, for me the `desert` colorscheme that comes with neovim also has darker terminal background when compared to non-terminal buffer.

**Comment by tuanbass** [comment]
Thanks @vhakulinen  for the response. 
> gnvim uses what ever colors neovim tells it to. You'll have to fiddle with your colorscheme.
> 
It's quite strange for me. Below is the comparison (left is nvim, right is gnvim), the difference is still occurred. 

![image](https://user-images.githubusercontent.com/9334023/174474093-0df93217-83a3-4fdb-abdc-713963e8d835.png)

I also tried with another nvim client (neovide), and they have the same problem. 
Do you think the difference comes from how GTK define the colorschme?

**Comment by vhakulinen** [comment]
> I also tried with another nvim client (neovide), and they have the same problem.

By having the same problem, do you mean that they (neovide) also has the same color(s) as gnvim?

> Do you think the difference comes from how GTK define the colorschme?

Gnvim doesn't use colors from gtk.

**Comment by tuanbass** [comment]
> By having the same problem, do you mean that they (neovide) also has the same color(s) as gnvim?

Sorry for the confusion as English is not my native language. 
Yes. I mean "neovide" has same colors as "gnvim". When original "nvim" has same colors with "original" terminal (It might because of nvim is run inside a "original" terminal I guess)

**Comment by vhakulinen** [comment]
> When original "nvim" has same colors with "original" terminal (It might because of nvim is run inside a "original" terminal I guess)

Thats indeed because its running inside the terminal.

I suggest you read through `:h highlight-args` and `:h terminal-config` to get a bit more in-depth view on coloring.
