### ISSUE TITLE
Fold closes when losing focus

### ISSUE THREAD

**Issue by urxvtcd** [vhakulinen/gnvim#192]
To reproduce:

1. Create two files. First is `minimal.vim`:
```
set nocompatible
au FocusLost * echo('Lost')
filetype plugin indent on
syntax on
set hidden
```
Then `minimal.txt`:
```
" {
" vim: foldmethod=marker foldlevel=0 foldmarker={,}
" It's a test
" }
```
3. Run gnvim on the two files:
```
gnvim minimal.txt -- -u minimal.vim
```
4. Open the fold with `za`
5. Move mouse so gnvim loses focus. The fold will close.

nvim version:
```
NVIM v0.8.0-dev-968-g09c6ce8c4
```

gnvim version:
```
gnvim v0.1.6-88-g6ba4737
```

Probably related to: https://github.com/equalsraf/neovim-qt/issues/591

**Comment by vhakulinen** [comment]
Gnvim was rewritten from ground up for gtk4. If the problem persists, feel free to reopen this issue.
