### ISSUE TITLE
Can't build project on Ubuntu 22.04.1.

### ISSUE THREAD

**Issue by Rid1-fz-06** [vhakulinen/gnvim#195]
I was trying to build this project, but it is failing again and again in the same place. The following is a screenshot of error
![image](https://user-images.githubusercontent.com/92540820/206238887-5db93c95-0646-4abf-b037-3512f4b9a1b9.png)

**Comment by vhakulinen** [comment]
Use the latest rust version (or in this case, at least version 1.62.0).
