### ISSUE TITLE
`cargo install --git` install method?

### ISSUE THREAD

**Issue by jarkkojs** [vhakulinen/gnvim#205]
Is the use of GNU makefile a constraint, or can it be theoretically relaxed? `build.rs` exists to overcome some of the difficulties but e.g. I have no idea whether Rust can package man pages or not. Perhaps README.md could document the reasoning? No demans to "fix" anything.

**Comment by vhakulinen** [comment]
As of d77e7fb00d0344608d9283654a387e935b941778, gnvim requires gio settings schema to be present. So the make file stuff is required.
