### ISSUE TITLE
Feature request: Disable externalized cmdline

### ISSUE THREAD

**Issue by badosu** [vhakulinen/gnvim#21]
I was not able to find how to disable externalized cmdline.

If it's not supported I'd like to suggest providing an option for it.

**Comment by vhakulinen** [comment]
Not supported currently. Should be quite trivial to implement support for it.

**Comment by vhakulinen** [comment]
Basically, we just need to provide flags/options to modify these lines: https://github.com/vhakulinen/gnvim/blob/master/src/main.rs#L112-L118

**Comment by badosu** [comment]
How is your plan for configuring? From what I see my first approach would be a cmd line argument, e.g. `--ext_cmdline=false`

**Comment by badosu** [comment]
@vhakulinen Thanks for the info, was very helpful.

I sent a PR, let me know if you have other plans for configurability :+1:
