### ISSUE TITLE
Blank page on startup

### ISSUE THREAD

**Issue by cedric-wall** [vhakulinen/gnvim#213]
Hello,
I've just tried to install gnvim but cannot start it, i'v just a blank window.
The error on terminal is : 

>thread 'main' panicked at 'failed to decode redraw notification: Syntax("error while decoding value: invalid length 7, expected struct WinViewport with 8 elements")', ui/src/components/appwindow/imp.rs:78:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

with backtrace=1 : 

>thread 'main' panicked at 'failed to decode redraw notification: Syntax("error while decoding value: invalid length 7, expected struct WinViewport with 8 elements")', ui/src/components/appwindow/imp.rs:78:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: gnvim::components::appwindow::imp::AppWindow::io_loop::{{closure}}
   4: glib::main_context_futures::<impl glib::auto::main_context::MainContext>::spawn_local_with_priority::{{closure}}
   5: glib::main_context_futures::TaskSource::dispatch
   6: g_main_context_dispatch
   7: <unknown>
   8: g_main_context_iteration
   9: g_application_run
  10: gnvim::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

I did the tests and have an error : 

>    Running tests/nvim.rs (target/debug/deps/nvim-ce971b82526dea01)
 running 2 tests
 test smoke_test ... ok
 test smoke_test_ui_attach ... FAILED

>failures:

>---- smoke_test_ui_attach stdout ----
thread 'smoke_test_ui_attach' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax("error while decoding value: invalid length 7, expected struct WinViewport with 8 elements")', lib/nvim-rs/tests/nvim.rs:93:91
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

>failures:
    smoke_test_ui_attach

>test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.10s

>error: test failed, to rerun pass `-p nvim-rs --test nvim`

`

I precise that i'm under archlinux. I compiled either stable and master version. All gtk4 libraries are installed.

Thanks

**Comment by vhakulinen** [comment]
The `win_viewport` event failure hints that you're running nvim version lower than 0.9. Gnvim requires nvim 0.9.

**Comment by cedric-wall** [comment]
indeed I had nvim 0.8.3, I didn't updated my system. It works well now, thank you very much
