### ISSUE TITLE
gnvim runs, but the executed page does not display anything

### ISSUE THREAD

**Issue by mohmmadView** [vhakulinen/gnvim#216]
**os** : GNU/Linux   localhost.localdomain 5.14.21-150400.24.41-default #1 SMP PREEMPT_DYNAMIC Fri Jan 13 08:55:22 UTC **2023 (1d4442d) x86_64 x86_64 x86_64 GNU/Linux
Operating System: openSUSE Leap 15.4
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.14.21-150400.24.41-default (64-bit)
Graphics Platform: X11
Processors: 12 × 12th Gen Intel® Core™ i5-12400
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® Graphics** 
### 1. make build  compiling  one warning   finished 
![makeBuild](https://github.com/vhakulinen/gnvim/assets/64944885/e43c5c94-97b4-4098-9fa9-5ece0569fba4)

### 2.Fix warning in  file row.rs
![fix-warning__file--row rs](https://github.com/vhakulinen/gnvim/assets/64944885/d89f23fd-99c4-47a6-9bdd-b7d23fbbb0a3)

### 3. test compiling  not warning  fix
![fix-warning__file--row rs](https://github.com/vhakulinen/gnvim/assets/64944885/ff1ac507-7e3c-40a1-ae51-0f3a309f3371)

### 5.run gnvim in terminal erorr 
![fix-Bug__RUST_BACKTRACE=1__NEW-BUG](https://github.com/vhakulinen/gnvim/assets/64944885/b68af24f-b71b-41c2-b731-b1d90034c124)

### **6. gnvim runs, but the executed page does not display anything**
![run__gnvim](https://github.com/vhakulinen/gnvim/assets/64944885/b57042b4-803e-40de-a677-4250ddff6e8b)

**Comment by vhakulinen** [comment]
Which neovim version are you using? Gnvim requires neovim 0.9.

**Comment by MahdiGMK** [comment]
I have the same issue

> $ nvim -v
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1696795921
system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/share/nvim"
Run :checkhealth for more info

**Comment by vhakulinen** [comment]
@MahdiGMK what is the error you're getting? The original error is from because of older nvim version.

**Comment by MahdiGMK** [comment]
> thread 'main' panicked at 'failed to decode redraw notification: Syntax("error while decoding value: invalid length 5, expected fewer elements in array")', ui/src/components/appwindow/imp.rs:78:26
stack backtrace:
   0:     0x559f554ad3e1 - <unknown>
   1:     0x559f554d4dff - <unknown>
   2:     0x559f554aa837 - <unknown>
   3:     0x559f554ad1f5 - <unknown>
   4:     0x559f554ae603 - <unknown>
   5:     0x559f554ae394 - <unknown>
   6:     0x559f554aeb89 - <unknown>
   7:     0x559f554aea87 - <unknown>
   8:     0x559f554ad846 - <unknown>
   9:     0x559f554ae7d2 - <unknown>
  10:     0x559f5533f4d3 - <unknown>
  11:     0x559f5533f913 - <unknown>
  12:     0x559f5539088a - <unknown>
  13:     0x559f5548d77a - <unknown>
  14:     0x559f5548ce38 - <unknown>
  15:     0x7f6e88799f19 - <unknown>
  16:     0x7f6e887f82b7 - <unknown>
  17:     0x7f6e88798112 - g_main_context_iteration
  18:     0x7f6e889cdaf6 - g_application_run
  19:     0x559f55344d55 - <unknown>
  20:     0x559f5536397a - <unknown>
  21:     0x559f553a0543 - <unknown>
  22:     0x559f55398849 - <unknown>
  23:     0x559f554a6b5b - <unknown>
  24:     0x559f55364355 - <unknown>
  25:     0x7f6e88498cd0 - <unknown>
  26:     0x7f6e88498d8a - __libc_start_main
  27:     0x559f5533fbd5 - <unknown>
  28:                0x0 - <unknown>

**Comment by MahdiGMK** [comment]
any idea? @vhakulinen

**Comment by mohmmadView** [comment]
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
You have new mail.

**Comment by szdytom** [comment]
I have encountered the same problem.
