### ISSUE TITLE
The issue "proc macro template_callbacks not expanded

### ISSUE THREAD

**Issue by mohmmadView** [vhakulinen/gnvim#217]
cannot find proc-macro-srv, the workspace /home/darksouls/Downloads/program/neovim/gnvim/gnvim-master is missing a sysroot" in Rust usually occurs when the required dependencies for the proc macro are not installed or configured correctly.

In this case, it seems that the gtk crate is being used along with a proc macro called template_callbacks. However, the proc macro is not being expanded because the required dependency proc-macro-srv is missing. Additionally, the error message suggests that the workspace at /home/darksouls/Downloads/program/neovim/gnvim/gnvim-master is missing a sysroot.

To resolve this issue, you can try the following steps:

Ensure that the gtk crate and its dependencies are properly configured in your Cargo.toml file. Make sure you have the latest version of the gtk crate and its dependencies.

Check if the proc-macro-srv dependency is specified correctly in your Cargo.toml file. If it is missing or not specified correctly, add it as a dependency.

Verify that you have the necessary build tools and libraries installed on your system for building GTK applications. This may include libraries like libgtk-3-dev or similar.

Check if there are any additional setup steps required for using the gtk crate or the template_callbacks proc macro. Consult the documentation or examples provided by the crate's maintainers for any specific requirements.

If the issue persists, try updating your Rust toolchain and dependencies to the latest versions. You can use the rustup tool to manage your Rust installation and update your toolchain.

If none of the above steps resolve the issue, please provide more information about your project structure, the versions of the gtk crate and proc-macro-srv dependency you are using, and any additional error messages or warnings you are encountering

**Comment by vhakulinen** [comment]
Whats the issue exactly?

**Comment by vhakulinen** [comment]
Closing due no feedback.
