### ISSUE TITLE
Font size is not respected in `guifont=`, neither are underscores instead of escapes

### ISSUE THREAD

**Issue by IkaSek** [vhakulinen/gnvim#221]
when i try to `set guifont=ZedMono\ Nerd\ Font\ Mono\ Bold:h16` or `set guifont=ZedMono_Nerd_Font_Mono_Bold` i get an invalid, non-monospaced font.

**Comment by vhakulinen** [comment]
You need `set guifont=ZedMono\ Nerd\ Font\ Mono\ Bold\ 16`.
