### ISSUE TITLE
panicked at lib/nvim-rs/src/types/gen.rs:765:18

### ISSUE THREAD

**Issue by jpotier** [vhakulinen/gnvim#222]
Decided to give a try to gnvim (0.3.1), but it only opens a window with no content:

```
thread 'main' panicked at lib/nvim-rs/src/types/gen.rs:765:18:
failed to decode message (Some("chdir"), Some([Array([String(Utf8String { s: Ok("/home/eeva/admin/nixos-config") })])]))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by vhakulinen** [comment]
Fixed in master.

**Comment by jpotier** [comment]
Would you recommend I update my distro's package to use the current head of "master" for end users, or should I want for a release/tag? @vhakulinen

**Comment by vhakulinen** [comment]
I would personally build from source.
