### ISSUE TITLE
'GenericError("Wait timeout (nvim_subscribe)")' error

### ISSUE THREAD

**Issue by ekremkaraca** [vhakulinen/gnvim#26]
Hey guys,

Thanks for the awesome project! I've tried to build it from source on Elementary OS 5.0 (based on Ubuntu 18.04) but I got error below (with RUST_BACKTRACE=1 option):

```shell
thread 'main' panicked at 'Failed to subscribe to 'Gnvim' events: GenericError("Wait timeout (nvim_subscribe)")', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: gnvim::build
  10: gio::auto::application::activate_trampoline
  11: g_closure_invoke
  12: <unknown>
  13: g_signal_emit_valist
  14: g_signal_emit
  15: <unknown>
  16: g_application_run
  17: <O as gio::application::ApplicationExtManual>::run
  18: gnvim::main
  19: std::rt::lang_start::{{closure}}
  20: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  22: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  23: main
  24: __libc_start_main
  25: _start

```

I have latest stable Rust compiler available (1.34) How can we fix it?

**Comment by vhakulinen** [comment]
Thats a runtime error. Check if https://github.com/vhakulinen/gnvim#running helps.

**Comment by ekremkaraca** [comment]
I've changed the OS I'm using. I don't know whether it continues (or not). I have no issue in new OS. So for now, I close this issue. If some has similar issue, we might consider reopening it.

Thanks for your help!

**Comment by ianchanning** [comment]
I got this error too - but it was because I had an old version of nvim on my system (v0.2.2). I upgraded via https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu to v0.3.7. Before that I'd probably just installed it from the standard package manager in Ubuntu.

**Comment by dbarnett** [comment]
I ran into this too on Debian Stretch. Consider an explicit error message if neovim is below a particular minimum version. Also in general consider a user-friendly error message that it couldn't connect to neovim instead of an ugly "GenericError Wait timeout" error from Rust.

**Comment by smolck** [comment]
> Consider an explicit error message if neovim is below a particular minimum version. Also in general consider a user-friendly error message that it couldn't connect to neovim instead of an ugly "GenericError Wait timeout" error from Rust.

@vhakulinen I like this idea of adding a helpful error message. We could get the latest version prior to running GNvim and then assert that it's greater than 0.3.4, maybe do something like this (would need some slight modification to check the 0.3.* part):

```rust
fn get_latest_nvim_version() -> i32 {
    let version = Command::new("nvim")
        .arg("--version")
        .output()
        .unwrap()
        .stdout;

    let version = String::from_utf8_lossy(&version);
    version
        .split("\n")
        .collect::<Vec<&str>>()[0]
        .split(".")
        .collect::<Vec<&str>>()[1]
        .parse::<i32>()
        .unwrap()
}

fn main() {
    assert!(get_latest_nvim_version() > 2, "Helpful Error Message");
}
```

This isn't necessarily the best way, just an example.

**Comment by badosu** [comment]
I think that would be a good idea, just remember to use the `nvim_path` option for the binary when provided.

**Comment by vhakulinen** [comment]
I think `:h nvim_get_api_info()` is better approach to getting the nvim version.
