### ISSUE TITLE
vim-multiple-cursor panic after pressing ctrl-n twice

### ISSUE THREAD

**Issue by alexlai97** [vhakulinen/gnvim#29]
`thread 'main' panicked at 'byte index 5 is out of bounds of ``', src/libcore/str/mod.rs:2010:9
note: Run with RUST_BACKTRACE=1 environment variable to display a backtrace.
fish: “gnvim” terminated by signal SIGILL (Illegal instruction)`

[multi-cursor](https://github.com/terryma/vim-multiple-cursors) plugin panics when pressing Ctrl-n twice with the above error.

**Comment by vhakulinen** [comment]
Can you try if #30 fixes this problem?

**Comment by alexlai97** [comment]
When I am in the master branch (c49d3b49608bf41b9d5678012cfc7428b401ca3e) now which (I believe) have merged these 2 pull requests #36 vhakulinen/support-doublewidth-chars, #30 vhakulinen/fix-cmdline-byte-index. And this problem occurs again with slightly different err [https://transfer.sh/WgsxG/err.log](url). 

However, `git checkout fix-cmdline-byte-index; cargo run` works fine (no error, behave correctly).

**Comment by vhakulinen** [comment]
Turns out that this is a bug in neovim it self: https://github.com/neovim/neovim/issues/10000

**Comment by smolck** [comment]
This should now be fixed as of this PR: [neovim/neovim#10344](https://github.com/neovim/neovim/pull/10344).

**Comment by vhakulinen** [comment]
Closing this, since afaik this was fixed by https://github.com/neovim/neovim/pull/10344.
