### ISSUE TITLE
Font configuration

### ISSUE THREAD

**Issue by badosu** [vhakulinen/gnvim#31]
I see that [gonvim](https://github.com/akiyosi/gonvim) renders the font in a different manner, the font seems to have more weight.

It improves with readability so I wonder how can an option for this be implemented in gnvim?

See below, `guifont=Fira\ Code:h13`, gnvim on the left, gonvim on the right:

![Screenshot from 2019-04-24 14-11-31](https://user-images.githubusercontent.com/347552/56679322-2c420900-669b-11e9-9f74-e36d807b6ffd.png)

**Comment by vhakulinen** [comment]
From top of my head, you could try `guifont=Fira\ Code\ Medium:h13`.

**Comment by badosu** [comment]
Ah, this seems to be the case. Thanks for the clarification.

Any reason for the discrepance? Do we use a default weight and gonvim another one?

**Comment by oxysoft** [comment]
Sorry to bump this old issue. Randomly stumbled upon this and was just wondering @badosu which color scheme you are using in this screenshot? I quite like these colors!

**Comment by badosu** [comment]
https://github.com/joshdick/onedark.vim
