### ISSUE TITLE
YCM Autocomplete Preview Blacked Out

### ISSUE THREAD

**Issue by TypeAndProgram** [vhakulinen/gnvim#35]
In gnvim, YouCompleteMe's auto complete preview is blacked out, as the below screenshot shows.

![Screenshot_20190427_181743](https://user-images.githubusercontent.com/46855713/56856125-9c5dc280-6919-11e9-9934-d7636c17a13e.png)

However, it is clearly readable in nvim from the terminal, as seen below.

![Screenshot_20190427_182324](https://user-images.githubusercontent.com/46855713/56856132-ac75a200-6919-11e9-87ad-c62bfaf3803e.png)

Could my neovim configuration (init.vim or .vimrc) be causing this, or is it something else? I can show my config files if needed.

**Comment by vhakulinen** [comment]
Which color scheme are you using? It probably is missing pmenu gui colors.

**Comment by TypeAndProgram** [comment]
I am using the molokayo color scheme by fmoralesc: [github.com/fmoralesc/molokayo](url). However, when I comment out the line which sets that colorscheme in my init.vim, it still does it. Could it be a plugin, like vim-airline?

**Comment by vhakulinen** [comment]
Do you have `GNVIM_RUNTIME_PATH` pointing to correct location? If you run `GNVIM_RUNTIME_PATH=./runtime cargo run` from the root of this repo, is the pmenu still black?

**Comment by TypeAndProgram** [comment]
Yes, the pmenu is still black. The terminal output shows a whole bunch of “Not supported option set” outputs, in addition to one which says “Received unknown redraw event: update_menu” if that helps. I can show a screenshot of the output if you need it.

**Comment by vhakulinen** [comment]
Can you try with `desert` colorscheme? Its one of the builtin ones.

**Comment by TypeAndProgram** [comment]
Pmenu is still black with desert color scheme.

**Comment by vhakulinen** [comment]
What nvim version are you using? Can you post your init.vim? Whats the output of `echo g:gnvim_runtime_loaded`?

**Comment by TypeAndProgram** [comment]
I am using nvim version 0.3.4, the output of the `echo` command is "g:gnvim_runtime_loaded" and here is my init.vim:

![Screenshot_20190428_081945](https://user-images.githubusercontent.com/46855713/56864991-74f50d00-698e-11e9-95e4-8d07a6974503.png)

**Comment by agraven** [comment]
The output of the command should be either 0 or 1. Make sure *not* to make `g:gnvim_runtime_loaded` a string, but writing the command exactly as
```
echo g:gnvim_runtime_loaded
```

**Comment by TypeAndProgram** [comment]
My bad, wasn’t running it in the right place, sorry about that. Anyways, in gnvim the output is 

E121: Undefined variable: g:gnvim_runtime_loaded

Also, when I exit the application with the ‘qa’ command, I get this output to the console:

(.:32354): GLib-CRITICAL **: 06:20:28.885: g_source_set_ready_time: assertion ‘source->priv != NULL’ failed

If that helps at all.

**Comment by vhakulinen** [comment]
This means that gnvim runtime files aren't loaded. See https://github.com/vhakulinen/gnvim#running

**Comment by TypeAndProgram** [comment]
Thank you very much! Please excuse my misunderstanding. The command given to test gnvim without installing it given at the start of the readme doesn't load the runtime files, namely this command:
`$ GNVIM_RUNTIME_PATH=./runtime cargo run`

Instead, I had to do this, filling in my specific path:
`$ GNVIM_RUNTIME_PATH=/path/to/gnvim/runtime cargo run`

Thanks again!

**Comment by vhakulinen** [comment]
Thanks for the info, I updated the readme.
