### ISSUE TITLE
Indentation issue in Terminal

### ISSUE THREAD

**Issue by badosu** [vhakulinen/gnvim#38]
### How to reproduce

- Open a `:terminal`
- Run `ls -al`

### What is expected

Output is correctly indented

### What happens

![Screenshot from 2019-04-30 15-47-13](https://user-images.githubusercontent.com/347552/56985670-41b5a800-6b5f-11e9-9333-dae16fb69c3e.png)

It works correctly on [gonvim](https://github.com/akiyosi/gonvim), so I don't think it's an externalized issue.

**Comment by vhakulinen** [comment]
Try running `reset` before `ls -as`. That looks more like a problem with the terminal it self than with gnvim.

**Comment by badosu** [comment]
Yeah, it works!

Do you mind sharing why reset fixes this?

**Comment by vhakulinen** [comment]
It has something to do with a think called terminal mode (if that is its name). `ncurses` and other TUIs (like nvim) changes the terminal mode settings which upon an unclean exit causes the terminal mode to be "invalid" when the terminal returns into the command prompt. `reset` command resets the terminal mode.

**Comment by badosu** [comment]
Thanks for the info @vhakulinen, currently I am prepending `reset` to my commands but I'll investigate why I have this discrepancy present, why it happens on gnvim but not on nvim or gonvim.

**Comment by smolck** [comment]
@vhakulinen Do you get this issue (and need to run `reset`) when you use `:terminal` in GNvim? If so, should we reopen this? I get this issue as well (even with [Nuake](https://github.com/Lenovsky/nuake)), and will hopefully be able to look into a possible fix (though, that may not be necessary; if you don't get this issue, I'm not sure if we should look into fixing it).

**Comment by vhakulinen** [comment]
This is not a problem with gnvim, but with the shell in use and/or nvim terminal. What ever is causing this issue in gnvim, will also occur with TUI if executed in the _exact_ same environment (same env vars and so on).

I've noticed that some prompts (`PS1`) causes this issue.

**Comment by badosu** [comment]
This does not happen for me in neovim.
