### ISSUE TITLE
GUI colors not always set automatically

### ISSUE THREAD

**Issue by sammoth** [vhakulinen/gnvim#39]
I have a light GTK theme but a dark vim theme. Is it possible to set the background of the command bar around the text so that it matches the vim colour scheme?

![2019-05-03-17:43:42 748535973](https://user-images.githubusercontent.com/3324352/57132876-264ed500-6dcb-11e9-84d6-38b2180ca567.png)

**Comment by sammoth** [comment]
![2019-05-04-02:52:03 447600358](https://user-images.githubusercontent.com/3324352/57162275-ef52e080-6e17-11e9-8e76-448247ee51f3.png)
On latest master it looks like this

**Comment by sammoth** [comment]
I have noticed that if I manually call `set guifont` after the GUI has loaded, it fixes the colours. However if I `set guifont` in init.vim, it doesn't work.

![2019-05-04-03:15:40 539407551](https://user-images.githubusercontent.com/3324352/57163640-f7148400-6e1b-11e9-8381-80c6d7e2ced3.png)

**Comment by sammoth** [comment]
I have worked around this issue with this unholy hack in my init.vim:
`autocmd VimResized * set guifont=Fira\ Code\ Medium:h10 | au! VimResized`

**Comment by vhakulinen** [comment]
Which GTK version and which nvim version are you using? The colors should be automatically set by gnvim's runtime files [here](https://github.com/vhakulinen/gnvim/blob/b721c778abc8d4156429307ab5773c275f99b19c/runtime/plugin/gnvim.vim#L45). Setting `guifont` (currently) has the side effect of setting the colors too (on some UI elements).

**Comment by sammoth** [comment]
GTK 3.24.8
nvim 0.3.5
gnvim 0.1.2-16-gb721c77

It doesn't work but if I change the line you linked in the runtime files to the following, it works:

```autocmd VimResized * call gnvim#set_gui_colors()```

I guess it is only working when it happens late enough in the gnvim startup process, and VimResized is called later than VimEnter, after some other part of the GUI is initialised.

**Comment by vhakulinen** [comment]
Hmh, `VimEnter` has worked just fine for me and afaik you're the only one experiencing problems with it. Can you do an echo (or something) on `VimEnter` autocmd to see if it even gets triggered?

**Comment by badosu** [comment]
I was able to reproduce this error earlier, switching from `neodark` to `onedark` colorscheme, workaround was to `source $MYVIMRC`.

Weirdly enough I can't now.

**Comment by badosu** [comment]
I found that prepending `sleep 100m` to `gnvim#set_gui_colors` is another workaround.

Perhaps neovim is calling VimEnter before gnvim can handle `SetGuiColors`
