### ISSUE TITLE
Feature request: option to show `menu` on inactive popupmenu completion items

### ISSUE THREAD

**Issue by vhakulinen** [vhakulinen/gnvim#41]
Gnvim's externalized popupmenu currently only show's `info` and `menu` items on the active completion item. There should be an option to show `menu` on inactive once too.

**Comment by smolck** [comment]
I would like to implement this, but I first want to verify I know what we want. Do you mean something like this?

![image](https://user-images.githubusercontent.com/46855713/60932834-5f04a200-a285-11e9-8cb5-208fbd40c5e4.png)

If not, and/or if you have an idea of how you want this to be implemented, please let me know.

**Comment by vhakulinen** [comment]
Only the `menu` item (e.g. in that image the `[LC]` part).
