### ISSUE TITLE
Can't seem to paste

### ISSUE THREAD

**Issue by hook-s3c** [vhakulinen/gnvim#46]
Doing the ol' ctrl+shift+v and nothing's happening

le sad

**Comment by vhakulinen** [comment]
Gnvim doesn't do anything regarding system clipboard. You can use `"+p` to paste from system clipboard (as usual).

**Comment by pshanoop** [comment]
@vhakulinen  `"+p` doesn't help on commands. I usually paste  on commands especially during `%s/blah/something/g`  kinda commands, This part usually covered by terminal emulators.

I don't know if there is any other solution to this cases.

**Comment by vhakulinen** [comment]
When in cmdline, you can paste from the `+` register bud doing `<c-r>` followd by `+`.

**Comment by pshanoop** [comment]
> When in cmdline, you can paste from the `+` register bud doing `<c-r>` followd by `+`.

I didn't know about this, Thanks for the info. :+1:
