### ISSUE TITLE
Scrollbar is not updated on wildmenu

### ISSUE THREAD

**Issue by badosu** [vhakulinen/gnvim#48]
When opening the menu, the scrollbar is not updated when reaching items outside the initial range.

How to reproduce:

- Start gnvim
- Type `:<Tab>`, the menu should open
- Type `<Tab>` until the end of the list is reached or drag the scrollbar on the right
- Notice the list is scrolled but scrollbar is pinned to the top

This happens on both external commandline and wildmenu. This does not occur on popupmenu.

If you have any pointers I'd be happy to try and fix this.

**Comment by vhakulinen** [comment]
Cant reproduce. Which gtk version are you using?

**Comment by smolck** [comment]
I was able to reproduce it, using the latest gnvim I think.

**Comment by vhakulinen** [comment]
I mean the gtk version installed on your system.

**Comment by smolck** [comment]
I am using gtk version 3.24.8.

**Comment by badosu** [comment]
It seems this is a known issue: https://gitlab.gnome.org/GNOME/gtk/issues/615

Gtk: 3.24.8

**Comment by smolck** [comment]
What's more strange is that this is not the case in the popupmenu: it scrolls just as expected. After moving around some of the code in wildmenu.rs and such to resemble that of the popupmenu, it didn't change the stuck scrollbar.

**Comment by vhakulinen** [comment]
I'm currently running ubuntu 16.04 and don't (currently) have access to machine with newer OS. I'll try to find some time and spin up a VM.

(I've noticed some inconsistencies with the scroll bars on different versions of gtk and its been PITA).

**Comment by badosu** [comment]
This is a minor issue atm., nothing that impedes workflow.

**Comment by smolck** [comment]
Just noticed that the horizontal scrollbar in the wildmenu doesn't move either when dragged. To reproduce, type out a long command in the wildmenu and move the scrollbar at the bottom: same behavior as the vertical scrollbar, it doesn't move.

**Comment by vhakulinen** [comment]
Gnvim was rewritten from ground up for gtk4. If the problem persists, feel free to reopen this issue.
