### ISSUE TITLE
Can run it on windows?

### ISSUE THREAD

**Issue by kdurant** [vhakulinen/gnvim#5]
I hope can run it on windows

**Comment by vhakulinen** [comment]
You should be able to run gnvim on windows. Just make sure you have the dependencies installed (gtk mainly).

For pre build binaries, I can't currently provide those since I don't have access to windows machine. I'll probably try out [appveyor](https://www.appveyor.com/) at some point, since thats what nvim is using to build their windows binaries (afaik).

**Comment by jloow** [comment]
I can confirm that it is possible to build and run gnvim on Windows. As with macOS you have to build without webkit2gtk, but otherwise it seems to be working fine.

**Comment by smolck** [comment]
> I can confirm that it is possible to build and run gnvim on Windows. As with macOS you have to build without webkit2gtk, but otherwise it seems to be working fine.

@jloow Was there anything aside from Rust and GTK3 that you needed to install?

**Comment by AoyamaSun** [comment]
> > I can confirm that it is possible to build and run gnvim on Windows. As with macOS you have to build without webkit2gtk, but otherwise it seems to be working fine.
> 
> @jloow Was there anything aside from Rust and GTK3 that you needed to install?

That's enough. And it is easy to install gtk via vcpkg.

**Comment by Simon-L** [comment]
I can myself confirm it also works using MSYS, using only the bundled `pacman` manager except for neovim that I downloaded and put somewhere.
`pacman -Sy mingw-w64-x86_64-gtk3 mingw-w64-x86_64-rust git`
Check if both rustc and cargo are available and build with the cargo command, including `--no-default-features`
Then from MSYS run using `./gnvim.exe --nvim=/path/to/nvim.exe`

**Comment by smolck** [comment]
So this issue can be closed then?

**Comment by Figuera** [comment]
I was able to build it using MSYS2 without incidents but when I start I get:

`Failed to build UI: Failed to start nvim: Failed to turn pipe into pollable stream`

Can anyone provide direction on dealing with this?

**Comment by vhakulinen** [comment]
> `Failed to build UI: Failed to start nvim: Failed to turn pipe into pollable stream`

Hmh, seems like glib/gio doesn't support pollable stdin/stdout streams on win32. Apparently there is open issue on glib's issue tracker related to this: https://gitlab.gnome.org/GNOME/glib/-/issues/2016.

Meanwhile you can use version of gnvim which didn't yet use gtk's subprocess for neovim (e.g. this commit: https://github.com/vhakulinen/gnvim/commit/5339bb566281d21b4f73a68fb54ef2113c77e27e).

It also looks like that there is this library called [wing](https://gitlab.gnome.org/GNOME/wing) (also mentioned in the glib's issue). You could try and see if loading that into gnvim helps.

**Comment by Figuera** [comment]
> Meanwhile you can use version of gnvim which didn't yet use gtk's subprocess for neovim (e.g. this commit: [5339bb5](https://github.com/vhakulinen/gnvim/commit/5339bb566281d21b4f73a68fb54ef2113c77e27e)).

This works!

**Comment by vhakulinen** [comment]
Follow up issue: https://github.com/vhakulinen/gnvim/issues/135
