### ISSUE TITLE
Feature Request: Show Symbol '+' to Indicate Unsaved Files in Tabline

### ISSUE THREAD

**Issue by smolck** [vhakulinen/gnvim#51]
The title essentially says it all. I think it would be nice to have some sort of visual indicator that a file has not been saved in the tabline when multiple tabs are open, like this in neovim: 

![image](https://user-images.githubusercontent.com/46855713/59067747-fdad7580-8877-11e9-81e3-acf280179638.png)

I would be happy to help implement this if it is wanted.

**Comment by smolck** [comment]
Looking at [line 86 in tabline.rs](https://github.com/vhakulinen/gnvim/blob/master/src/ui/tabline.rs#L87), it seems that neovim_lib doesn't provide the '+' symbol to gnvim for use in the tabline, even though it is shown in the tabline in neovim in the terminal. Is this intended behavior?

**Comment by badosu** [comment]
See https://github.com/neovim/neovim/blob/master/runtime/doc/ui.txt#L612

Neovim only sends the tabs and names.

**Comment by smolck** [comment]
Interesting. It seems that [Gonvim](https://github.com/akiyosi/gonvim) is the same story: no visual indication for a change to a file in the tabline. [Oni](https://github.com/onivim/oni) does support this however (from what I can see in the README's screenshot), so maybe looking at how it is implemented over there could help. I imagine this may take a good bit of code and or refactoring to get it working though, possibly more than it's worth?

**Comment by badosu** [comment]
I am not familiar with `neovim-lib` but if you can eval vimscript you could theoretically retrieve `:echo &mod[ified]` as 0 or 1.

**Comment by smolck** [comment]
Hmm. I'll look into it. Thank you!

**Comment by smolck** [comment]
Using neovim-lib it is possible to call `:buffers` in the `update` function in tabline.rs using the `command_output` function (if `update` is passed a copy of the neovim instance). So then we could just split up the command's returned `String` to get the names of any modified buffers, check if any of the tabs have the same names as the modified buffer/buffers, and if so add `+` to that tab's label in the tabline. I will try to implement this solution locally and see where it gets me.

See https://docs.rs/neovim-lib/0.6.1/neovim_lib/neovim_api/trait.NeovimApi.html#tymethod.command_output

**Comment by vhakulinen** [comment]
After some fiddling, this should be quite trivial: pass `Neovim` to the `update` method, and the for each tabpage, for each window, get the buffer and check what the value of `mod` option is. If any of those is `true`, then the tabpage contains modified buffers.

**Comment by smolck** [comment]
Thank you, didn’t see that!

**Comment by vhakulinen** [comment]
Fixed in #52
