### ISSUE TITLE
Cursor Appears at Bottom of Screen When Moving Around File With Keyboard

### ISSUE THREAD

**Issue by smolck** [vhakulinen/gnvim#53]
When moving in a file with the keyboard (`j`, `k`, `l`, `h`), the cursor first appears at the bottom right of the screen and then moves to where it should be in the file (This is a picture of it while the cursor is at the bottom right of the screen. After this, it appeared back at the correct position):

![image](https://user-images.githubusercontent.com/46855713/59311870-a7be4080-8c70-11e9-8796-45bf5aaa8907.png)

It does this erratically, and I have only noticed it while _holding down_ the keys to move (most notably when moving up or down in a file).

The following diff stops this behavior, but I imagine this is not an ideal solution and only masks the real problem (something with `neovim_lib`, maybe?):
```diff
diff --git a/src/ui/grid/grid.rs b/src/ui/grid/grid.rs
index b2e61b4..0af02df 100644
--- a/src/ui/grid/grid.rs
+++ b/src/ui/grid/grid.rs
@@ -57,7 +57,7 @@ pub struct Grid {
     /// EventBox to get mouse events for this grid.
     eb: EventBox,
     /// Internal context that is manipulated and used when handling events.
-    context: Arc<ThreadGuard<Option<Context>>>,
+    pub context: Arc<ThreadGuard<Option<Context>>>,
     /// Pointer position for dragging if we should call callback from
     /// `connect_motion_events_for_drag`.
     drag_position: Arc<ThreadGuard<(u64, u64)>>,
@@ -326,6 +326,11 @@ impl Grid {
         let mut ctx = self.context.borrow_mut();
         let ctx = ctx.as_mut().unwrap();
 
+        // Prevents cursor from appearing at bottom of screen
+        if row == ctx.rows.len() as u64 - 1 {
+            return;
+        }
+
         // Clear old cursor position.
         let (x, y, w, h) = ctx.get_cursor_rect();
         ctx.queue_draw_area
```

**Comment by badosu** [comment]
I don't think this is an issue, I tried debugging it and noticed neovim's TUI presents the same behavior.

Seems to be an indicative of the current motion you're performing, e.g. `gg` gets you to the top of the page on normal mode, type the first `g` and notice it's shown there without flickering.

**Comment by badosu** [comment]
It could be an issue if neovim provides an externalized api call to receive this data so that we can present it nicely.

**Comment by smolck** [comment]
I have never noticed that the same thing happens in the TUI, good spot. I do understand that it is intended behavior for the keys you press to appear in the bottom, but I don't understand the purpose of the cursor appearing at the bottom for a split second, since that doesn't give any information.

Could it be a bug in neovim? Vim's TUI doesn't do that. Also, it is inconsistent in when it appears. It happens only every now and again in neovim's TUI, but in gonvim (which does it too) it appears almost every time the cursor moves when holding a motion command.

**Comment by badosu** [comment]
> Could it be a bug in neovim? Vim's TUI doesn't do that.

It does for me. Not sure if it could be considered a bug, perhaps a UI issue.

> Also, it is inconsistent in when it appears. It happens only every now and again in neovim's TUI, but in gonvim (which does it too) it appears almost every time the cursor moves when holding a motion command. Gnvim is somewhere in the middle.

Perhaps this is due to how often and fast the screen is drawn.

**Comment by smolck** [comment]
Yeah, good points. It seems that this is something that would be best solved in vim/neovim itself, and that's if it can be considered an issue.

**Comment by vhakulinen** [comment]
Neovim it self is sending the commands to put the cursor in the bottom row.

**Comment by badosu** [comment]
Seems like the `showcmd` can be externalized: https://github.com/neovim/neovim/blob/master/runtime/doc/ui.txt#L735

**Comment by bfredl** [comment]
Trying to fix the cursor issue here https://github.com/neovim/neovim/pull/10221
