### ISSUE TITLE
Issues with font and colors

### ISSUE THREAD

**Issue by Mte90** [vhakulinen/gnvim#6]
![screenshot_20190227_145719](https://user-images.githubusercontent.com/403283/53495344-14397900-3aa0-11e9-9a2f-80afa81c5f34.png)
On the left there is gnvim and right neovim on konsole in Kde.
They are using the same settings that are avalaible at https://github.com/mte90/my-scripts/blob/master/vim/vimrc
As I can see the colors are lightly differents but also the font is not configured rightly.

**Comment by Mte90** [comment]
If can be helpful this is the shell output:
```
Not supported option set: arabicshape
Not supported option set: ambiwidth
Not supported option set: emoji
Not supported option set: guifontset
Not supported option set: guifontwide
Not supported option set: showtabline
Not supported option set: termguicolors
Not supported option set: ext_linegrid
Not supported option set: ext_hlstate
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: termguicolors
Received unknown redraw event: set_icon
Received unknown redraw event: mouse_on
Not supported option set: showtabline
Received unknown redraw event: mouse_on
Received unknown redraw event: update_menu
Received unknown redraw event: update_menu
Received unknown redraw event: mouse_on
Received unknown redraw event: set_icon
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
```

**Comment by vhakulinen** [comment]
What colorscheme are you using?

For font, gnvim fails to find your font and defaults to some non-monospace font. Try `:set guifont=Monospace`.

**Comment by Mte90** [comment]
I am using https://github.com/Valloric/vim-valloric-colorscheme
For the font do you have any suggestions to let us the right one? Maybe the absolute path?

**Comment by Mte90** [comment]
Just in case I am using the font from https://github.com/ryanoasis/nerd-fonts

**Comment by vhakulinen** [comment]
For valloric colorscheme, this is where it sets the `Normal` for gui: https://github.com/Valloric/vim-valloric-colorscheme/blob/master/colors/valloric.vim#L97 and here you can see that it sets different `Normal` color for terminal: https://github.com/Valloric/vim-valloric-colorscheme/blob/master/colors/valloric.vim#L186. Looks like the colorscheme you're using has different colors for terminal and gui.

For fonts, check if your font is findable by other programs and that the name is correct. Looking at your vimrc, you have `set guifont=DroidSansMono\ Nerd\ Font\ 11`, but by looking the nerd fonts readme, it probably should be `set guifont=Droid\ Sans\ Mono\ Nerd\ Font`. To set the height, use `:h11` at the end of the font name (e.g. `set guifont=Droid\ Sans\ Mono\ Nerd\ Font:h11` or `:set guifont=DroidSansMono\ Nerd\ Font:h11` depending on the proper font name).

**Comment by Mte90** [comment]
You are right about the font, with your suggestion now is right :-D

About the colorscheme I am not sure about what to do to usethe same colorscheme also in gnvim.

**Comment by vhakulinen** [comment]
If you want to use the same color scheme, you'll have to patch it your self (e.g. dig up the correct colors from your terminal color scheme and assign them to the `gui` colors in the `vim-valloric-colorscheme` file).

**Comment by Mte90** [comment]
Thanks so you are saying that my colorscheme is not compatible with vim gui but only with terminal UI.
I will check!

**Comment by vhakulinen** [comment]
Most likely.

**Comment by Mte90** [comment]
Thanks I updated my colorscheme and now works pretty well https://github.com/mte90/my-scripts/blob/master/vim/colors/valloric.vim with gnvim :-)

**Comment by ianchanning** [comment]
I'm getting the same:

```
$ gnvim ~/.vimrc 
Not supported option set: arabicshape
Not supported option set: ambiwidth
Not supported option set: emoji
Not supported option set: guifontset
Not supported option set: guifontwide
Not supported option set: showtabline
Not supported option set: termguicolors
Not supported option set: ext_linegrid
Not supported option set: ext_hlstate
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: termguicolors
Not supported option set: termguicolors
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Failed to turn input event into nvim key (keyval: 65506)
```

Initially I had a 24-bit solarized `colorscheme` in my `.vimrc`:

```vimrc
" Vundle "{{{
" ======

set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'lifepillar/vim-solarized8'
...
```

But I removed that and I still get the errors.

**Comment by smolck** [comment]
@ianchanning Are you having any problems with GNvim, or are you only speaking of the messages printing out to the console? Those messages are there mainly for debugging purposes.

**Comment by ianchanning** [comment]
I also get the same errors if I completely remove my `.vimrc` file.

**Comment by ianchanning** [comment]
Ah ok, it maybe these are just debugging messages which I can ignore. 

I'm getting the following log messages when I type `:`:
```
Failed to turn input event into nvim key (keyval: 65506)
```

But that's probably a separate issue.

However since `Not supported option set: termguicolors` it will mean that my 24-bit colorscheme might have problems.

**Comment by smolck** [comment]
> @smolck Thanks for the reply. Ah ok, it maybe these are just debugging messages which I can ignore.

@vhakulinen Maybe we should remove these messages (or remove them in releases). Are they necessary anymore? (We may have enough output for debugging between all of the issues mentioning them 😂 ) They seem to make the user think there’s a problem when there isn’t.

> I'm getting the following log messages when I type `:`:
> 
> ```
> Failed to turn input event into nvim key (keyval: 65506)
> ```
> 
> But that's probably a separate issue.

They’re just more debugging messages (`:` doesn’t usually have any meaning by itself, I don’t think, unless you give it meaning, which is why GNvim outputs that message; it isn’t an nvim key).

> However since `Not supported option set: termguicolors` it will mean that my 24-bit colorscheme might have problems.

If you have any problems with it please let us know (GNvim automatically sets `termguicolors` since it _does_ support them). You shouldn’t though have any though (I’d have to look at why it outputs that message; I think it always does, have to check though), but I think you can ignore it.

**Comment by vhakulinen** [comment]
All that output can be ignored. The `Not supported option set: ...` messages are send by nvim but gnvim doesn't handle them. We _could_ handle them, if there was something we could do - but rather we should just silence them.

**Comment by ianchanning** [comment]
@smolck fantastic thanks, colours and fonts look good, even tested it with the fractional fonts to match my terminal and it looks great
