### ISSUE TITLE
Add Project Board(s)

### ISSUE THREAD

**Issue by smolck** [vhakulinen/gnvim#60]
Setting goals with a project board (or boards) for GNvim's next release(s) would help contributors to know where to focus their efforts and tell them what GNvim wants to become. That way, they would know what features should (and shouldn't) be added, what bugs need to be handled/fixed (before the next release), refactors that should be done, etc. (and it would likely help with efficiency).

**Comment by badosu** [comment]
I am not sure this is required at this stage, gnvim has a small amount of contributors that would likely not benefit on the possibly increased pressure to achieve deadlines/goals. 

I might be wrong though.

**Comment by smolck** [comment]
> . . . gnvim has a small amount of contributors that would likely not benefit on the possibly increased pressure to achieve goals.

I mean it more as a guide to help with improving GNvim and directing efforts than any sort of pressure. That way, any new (and also current) contributors would have an idea of what is wanted, without having to ask @vhakulinen; he would have already laid it out. It would probably help him out too, since I imagine he has a lot that he wants to do with GNvim but can’t work on currently due to limited time (correct me if I’m wrong). For example, we could know to start implementing a feature he wants added and he’d only have to help on areas he felt he should.

**Comment by vhakulinen** [comment]
I'd rather create milestones and use those to track/prioritize issues and pull requests. IMO actual project boards doesn't really fit for small open source projects without dedicated team working on it.

**Comment by vhakulinen** [comment]
Also, I created a [gitter](https://gitter.im/gnvim/community) room for gnvim.
