### ISSUE TITLE
Crash when delete full width (CJK) character

### ISSUE THREAD

**Issue by cohama** [vhakulinen/gnvim#62]
Minimal step to reproduce.
1. open gnvim
2. paste `あ`
3. press `x` to delete
4. crash

gnvim 0.1.4-8-g5bf01b9

**Comment by badosu** [comment]
Hmm.. I use the same version and can't reproduce

**Comment by smolck** [comment]
> We need to provide a way to pass arguments to nvim . . .

@badosu, considering that we’re changing (hopefully) the way GNvim is configured with #61 and probably removing flags, do you think I should add a way to do this there? It shouldn’t be too hard; either add a flag like `—nvim` to signify that the following args are for nvim, default to sending the args given to `gnvim` command to nvim, or similar. Alternatively, I could submit a PR specifically for this if necessary.

**Comment by smolck** [comment]
@badosu There is a way to pass arguments to Neovim from the gnvim command. Just do this:
`gnvim -- -u NORC`.

@cohama Can you try running `gnvim -- -u NORC` and see if the problem persists?

**Comment by vhakulinen** [comment]
Should be fixed now.

**Comment by cohama** [comment]
Confirmed! Thanks!
