### ISSUE TITLE
WM_CLASS property not set

### ISSUE THREAD

**Issue by smolck** [vhakulinen/gnvim#64]
Not sure if we want to address this, but I ran into it when trying to configure GNvim to open automatically on a specific workspace in i3(-gaps). The WM_CLASS property is not set for GNvim, and so WM_CLASS defaults to `"."`.

If you want to see this for yourself, open up GNvim and a terminal, run `$ xprop | grep "WM_CLASS"` (or `$ xprop`) and click on the GNvim window. The output in the terminal will be something like this/include this:

`WM_CLASS(STRING) = ".", "."`

I don't know how this impacts usage by other users, but for i3 it hinders the ability to assign GNvim to a workspace, since it is done via this class property; in i3, all applications, regardless of their class, will satisfy the class property `"."`, so one can't specifically assign GNvim to a workspace (all applications will be assigned to said workspace that aren't already assigned elsewhere).

The following commit fixes this problem by setting GNvim's `WM_CLASS` property to `GNvim` in main.rs:
```diff
diff --git a/src/main.rs b/src/main.rs
index ef0cc46..5a44035 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -146,6 +146,7 @@ fn main() {
         gtk::Application::new("com.github.vhakulinen.gnvim", flags).unwrap();
 
     glib::set_application_name("GNvim");
+    gdk::set_program_class("GNvim");
     gtk::Window::set_default_icon_name("gnvim");
 
     app.connect_activate(move |app| {
```

It may also be possible to set this property via the gnvim.desktop file, but I have not tested enough to confirm this is true (see [this article](https://stackpointer.io/unix/linux-get-wm-class-window/628/)). It may be worth noting that some applications allow this to be set/changed via a `--class` CLI flag ([Termite](https://github.com/thestinger/termite) used here as an example, this works with Firefox too): `$ termite --class <class name>`.

See also:
https://developer.gnome.org/gdk3/stable/gdk3-General.html#gdk-set-program-class
https://gtk-rs.org/docs/gdk/fn.set_program_class.html

**Comment by vhakulinen** [comment]
Fixed in 233b9cff98c4d06041de1a5fe27e201ebc686559
