### ISSUE TITLE
Ability to specify the default Markdown code block language for tooltips

### ISSUE THREAD

**Issue by YaLTeR** [vhakulinen/gnvim#76]
Rust documentation uses plain code blocks without the language. It would be nice to be able to set the fallback language for plain code blocks in cursor tooltips (for example, as an argument to `gnvim#cursor_tooltip#show`).

**Comment by vhakulinen** [comment]
Are you using gnvim-lsp? The relevant part of the code is [this](https://github.com/vhakulinen/gnvim-lsp/blob/f137b5362dab3c1897c76f50f761e59411effc78/autoload/gnvim_lsp/hover.vim#L133). IMO its up to the lsp client/server to supply the correct markdown.

**Comment by YaLTeR** [comment]
I hacked together a `LanguageClient-neovim` version of `gnvim-lsp`, and I'm using it with [`rust-analyzer`](https://github.com/rust-analyzer/rust-analyzer) as the server. Should I open an issue on `rust-analyzer` then, for it to add the `rust` language specifier to the code blocks from the comments?

**Comment by vhakulinen** [comment]
Yes.

**Comment by YaLTeR** [comment]
I submitted an issue to `rust-analyzer` (https://github.com/rust-analyzer/rust-analyzer/issues/1540) and it looks like it'll get fixed on that side indeed.
