### ISSUE TITLE
Font rendering issue (synthetic font styles)

### ISSUE THREAD

**Issue by clason** [vhakulinen/gnvim#84]
I have a persistent issue with font rendering under `gnvim` (on Linux, OpenSUSE Tumbleweed, built from master) where some monospace fonts do not render correctly if the color scheme uses (synthetic) bold: e.g., with the `Inconsolata` font and the colorscheme https://github.com/mhartington/oceanic-next, I get the following behavior:

1. `set ft=tex`
2. type `\foobarbaz{quux}` (doesn't matter as long as it starts with `\` and ends with `{` -- the longer, the more obvious the error)

Result in gnvim:
![Screenshot_20190725_122743](https://user-images.githubusercontent.com/2361214/61867588-dd914e80-aed7-11e9-962c-f3bf2a2a99a3.png)
(note the incorrect widths of the text in red)

Result in TUI (gnome-terminal 3.32.2 using VTE 0.56.3):
![Screenshot_20190725_123911](https://user-images.githubusercontent.com/2361214/61868244-45946480-aed9-11e9-86a7-5c43e6283aec.png)
(note that the text in red is *not* fake-bolded).

The same font and scheme also renders correctly in `neovim-qt` and `konsole`. I have the same issue in `neovim-gtk`, so it's probably an issue with the Cairo or Pango font rendering. I've searched around and found no real solution on the net; if anyone can point me in the right direction, that'd be appreciated. (Let me know what information you need: versions of which software etc.)

**Comment by vhakulinen** [comment]
Can you show how it looks in the TUI and paste the code here in the github issue tracker?

**Comment by clason** [comment]
@vhakulinen Sorry, took some time to get back to the same machine. I updated (and simplified) the original issue.

**Comment by smolck** [comment]
@clason What version of GNvim and GTK are you using? Can't seem to reproduce with Inconsolata and OceanicNext on latest master (this is GNvim):

![image](https://user-images.githubusercontent.com/46855713/62053241-d40c2d00-b1dc-11e9-9798-8e4e47585b00.png)

My GTK version is 3.24.10

**Comment by clason** [comment]
@smolck It's GNvim HEAD (but the issue has been around since I started looking at GNvim), and GTK 3.32.2 -- same as gnome-terminal, which doesn't show the issue. I don't believe it's a GTK issue, but rather Pango (similarly to #85) -- what's your Pango version?

**Comment by smolck** [comment]
@clason Just updated pango recently, and I get the same problem with Fantasque Sans Mono Bold and Iceberg.vim colors. I'm almost certain this issue and #85 are resulting from pango's update, since I didn't see the problem before updating (and [neovim-gtk/208](https://github.com/daa84/neovim-gtk/issues/208) seems to point towards it being a pango issue as well).

@vhakulinen #85 is (I believe) caused by the pango update too, so it and this issue are only different results of the pango update. It seems that a refactor will need to take place to fix these issues, and I'm happy to help where I can. Note that I also am having a problem where the statusline is not showing on the bottom of GNvim, which I think is caused by the update too. We may want to open an issue on how we want to do the refactor, but I don't know if that is necessary.

**Comment by smolck** [comment]
After some debugging, the calculations from [this function (`CellMetrics::update` in context.rs)](https://github.com/vhakulinen/gnvim/blob/1d8a0425b851cd4cb821c38ac2b6a50c6b52fd07/src/ui/grid/context.rs#L222) are different with the new pango version (here is the output of `dbg!(&self)` at the end of the function):

__After__ the pango update:
```rust
[src/ui/grid/context.rs:235] &self = CellMetrics {
    height: 18.3193359375,
    width: 7.0,
    ascent: 14.330078125,
    decent: 3.9892578125,
    underline_thickness: 2.0,
    underline_position: -1.0,
    line_space: 0,
    font_desc: FontDescription(
        Boxed {
            inner: ForeignOwned(
                0x0000556f53c936d0,
            ),
        },
    ),
}
```

__Before__ the pango update:
```rust
[src/ui/grid/context.rs:235] &self = CellMetrics {
    height: 19.0,
    width: 8.0,
    ascent: 15.0,
    decent: 4.0,
    underline_thickness: 2.0,
    underline_position: -1.0,
    line_space: 0,
    font_desc: FontDescription(
        Boxed {
            inner: ForeignOwned(
                0x0000561f5b7c5d30,
            ),
        },
    ),
}
```

It's like the new update made things more precise or something? Not really sure why this difference is there?

CC: @badosu @vhakulinen

**Comment by clason** [comment]
@smolck Yes, see https://blogs.gnome.org/mclasen/2019/07/27/more-text-rendering-updates/ (under "Subpixel positions"). From my own concurrent tries to get at the bottom of this, subpixel hinting is my main suspect as well (since Inconsolata, but not other fonts, got unbroken by reverting the hinting to vendor default -- this was under 1.43, though).

**Comment by smolck** [comment]
So, in theory, we could fix this by adding support for subpixel positioning in GNvim (note that I don’t know much about how font rendering and such works)? Would that be feasible?

**Comment by vhakulinen** [comment]
Seems like you already hunted down the likely source of this bug.

A poor man's solution for fixing this would be to round up the cell metrics, but I'd rather see gnvim to support subpixel positioning if possible.

**Comment by clason** [comment]
@vhakulinen To be honest, I had the same issue already with pango 1.43, so that can't be the whole story (at least for me). Still, the pango 1.44 issue seems to be much more widespread, and a fix for that just might work for me as well!

**Comment by smolck** [comment]
> . . . but I'd rather see gnvim to support subpixel positioning if possible.

@vhakulinen Do you have an idea of how you’d want this done? I haven’t looked into it, but it shouldn’t be too difficult, right?

**Comment by vhakulinen** [comment]
I'm not sure yet, but ceiling the values we pass into `queue_draw_area` could be a starting point and see how that helps. AFAIK just casting floats to i32 (as we do currently) just drops the decimals effectively flooring the values.

**Comment by last-partizan** [comment]
@vhakulinen take a look at this commit in pango: https://gitlab.gnome.org/GNOME/pango/commit/77b78746c901f95ca45a9ccffe9c32a38c0fb32b

**Comment by smolck** [comment]
> . . . take a look at this commit in pango: https://gitlab.gnome.org/GNOME/pango/commit/77b78746c901f95ca45a9ccffe9c32a38c0fb32b

Once this hits Arch/the AUR, I'll test it (it hasn't yet AFAIK). If our problems are due to subpixel positioning, that commit should fix it. If not, then we'll need to keep searching for the actual problem. Either way, I'm glad they decided to default to rounding as it used to be.

**Comment by leowzukw** [comment]
> Disclaimer: I took the occasion to learn how PKGBUILD works. I could be completely wrong.

It looks like `pango-git` in AUR always builds from the last commit.

When I tried to install package `pango-git`, it reported installing version from commit [e160a3cd](https://gitlab.gnome.org/GNOME/pango/commit/e160a3cdf059ab8cd17a66655aa08616876d3376), which is current master and after [77b78746](https://gitlab.gnome.org/GNOME/pango/commit/77b78746c901f95ca45a9ccffe9c32a38c0fb32b). This would be consistent with [pkgver autobump](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver()_function) and what we can read from the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pango-git&id=49cd1b0bc6d92b6804c21c416101dde19a7c5681#n26) of `pango-git`.

*Spoiler alert*: I had the problems described here with pango 1.44, solved by downgrading to 1.43 but not solved by upgrading to master.

**Comment by smolck** [comment]
@leowzukw Are you sure? At the bottom of the package details for [pango-git on the AUR](https://aur.archlinux.org/packages/pango-git) it says `Last Updated: 2019-08-02 01:00`, and the commit in question was authored on August 3rd at 7:59pm according to GitLab (says that time when I hover over the `1 day ago` part of `authored 1 day ago` under the commit on [this page](https://gitlab.gnome.org/GNOME/pango/commits/master)). I assumed that meant pango-git's outdated, but I may be wrong.

**Comment by leowzukw** [comment]
I can’t be positive but when you try manually [building](https://wiki.archlinux.org/index.php/Arch_User_Repository#Build_and_install_the_package) the package, the `makepkg` commands modifies the version number in the `PKGBUILD` file.

**Comment by leowzukw** [comment]
Found [something else](https://wiki.archlinux.org/index.php/Arch_User_Repository#What_is_the_difference_between_foo_and_foo-git_packages?) arguing for the auto-update feature.

> Because these packages download the latest available source when you execute makepkg

**Comment by smolck** [comment]
Hmm, didn't know that. I guess we had better keep looking into why the problems arise. Thanks @leowzukw for the info!

**Comment by vhakulinen** [comment]
Further pango 1.44 discussions in #85. Original issue here doesn't seem to be related to pango 1.44.

**Comment by vhakulinen** [comment]
After much of research: you can either use a font that has a bold styled font or disable synthetic styles system wide (I guess by removing `/etc/fonts/conf.d/90-synthetic.conf`).

We could also, in gnvim, load up fonts manually and thus bypassing any creating of synthetic/fake fonts withing gtk/pango/fontconfig and what not or detect synthetic fonts in the rendering process by calling `pango_font_face_is_synthesized` and skipping bold styles if that returns true. And PRs for this are welcome. I'm not too familiar with the whole font pipeline and thus don't have much more pointers for where to look at.

**Comment by clason** [comment]
@vhakulinen Thank you! Disabling synthetic bold through the `conf.d` file is a good workaround that works for my original problem.

**Comment by vhakulinen** [comment]
Be aware that the `/etc/fonts/conf.d/90-synthetic.conf` affects the whole system.

**Comment by clason** [comment]
I know, but a) it doesn't seem to affect Qt applications and b) I had the same issue in other pango-based editors, so for me the global effect is reasonable.

**Comment by isovector** [comment]
I just ran into this issue today, installing gnvim from AUR. The workaround above didn't resolve the issue for me.

```
$ pacman -Q | grep "pango\|gnvim"
gnvim-git r273.65846f4-1
pango 1:1.44.7+11+g73b46b04-1
```
