### ISSUE TITLE
Incorrect " ╭" and " ╰" rendering with Fira Code... sometimes

### ISSUE THREAD

**Issue by YaLTeR** [vhakulinen/gnvim#87]
With `set guifont=Fira\ Code:h11`,
```
 ╭──
 │
 │
 │
 ╰──
```
(note one space before the corner symbols)

renders as:
![image](https://user-images.githubusercontent.com/1794388/62268523-f40e3d00-b3e4-11e9-80b4-bfbdc87fcf16.png)
instead of (terminal nvim, also in Firefox where ligatures work, so it's not a ligature issue):
![image](https://user-images.githubusercontent.com/1794388/62268549-07b9a380-b3e5-11e9-8900-b7fd6e6f89d4.png)
However, with the corner selected, it does render properly:
![image](https://user-images.githubusercontent.com/1794388/62268611-3768ab80-b3e5-11e9-819b-f85e9a895fb0.png)

Interestingly enough, with `set guifont=monospace:h11`, which should in theory resolve to the exact same font:
```
┌ [I] ~
└─ fc-match Fira\ Code
FiraCode-Regular.otf: "Fira Code" "Regular"
┌ [I] ~
└─ fc-match monospace
FiraCode-Regular.otf: "Fira Code" "Regular"
```
it does render correctly:
![image](https://user-images.githubusercontent.com/1794388/62268724-9a5a4280-b3e5-11e9-94ec-950bf871ebe8.png)

**Comment by vhakulinen** [comment]
Do you happen to have pango v1.44?

**Comment by YaLTeR** [comment]
I reported this before upgrading to 1.44, but on 1.44 the behavior is the same (plus some broken pixels).

**Comment by vhakulinen** [comment]
This _might_ be a problem with firacode it self. With ubuntu 18.04's "text editor", that same text is also rendered incorrectly:

![image](https://user-images.githubusercontent.com/4594126/62613745-bb092780-b912-11e9-9c6f-dec56d01e5d9.png)


Ref: https://github.com/tonsky/FiraCode/blob/7a5965a5f656fff5b3963d23c330e55b4d2e8e56/CHANGELOG.md#L8
> Added Box Drawing Light Arcs U+256D ╭ U+256E ╮ U+256F ╯ U+2570 ╰ [#702] [#714] [#725]
^ Thats on a wip release

Ref: https://github.com/tonsky/FiraCode/issues/349

Also search results for "U+256D" (`╭` character), https://github.com/tonsky/FiraCode/search?q=U%2B256D&type=Issues

**Comment by YaLTeR** [comment]
Ah, yep, that was it. The lastest master Fira Code doesn't have that issue.
