### ISSUE TITLE
Add configuration documentation

### ISSUE THREAD

**Issue by romgrk** [vhakulinen/gnvim#9]
How can gnvim be configured? More specifically, I'd like to change the font.

**Comment by justinmk** [comment]
`:help 'guifont'` should work

**Comment by vhakulinen** [comment]
Yea, for font use `guifont` (e.g. ´:set guifont=Fira\ Code:h12`). Only `h` option after the font name is currently supported.

**Comment by waseem** [comment]
@vhakulinen Where exactly should I put this configuration? I tried putting it in `~/.config/nvim/ginit.vim` and `~/.config/gnvim/init.vim`. In both cases my configuration did not load.

**Comment by smolck** [comment]
@waseem It goes in your normal init.vim, i.e. `~/.config/nvim/init.vim`. To only do so for GNvim you should be able to do something like this:

```viml
if exists('g:gnvim')
    " GNvim-specific configuration goes here
    set guifont=Fira\ Code:h12
endif
