### ISSUE TITLE
Cursor squished after coming back to normal mode

### ISSUE THREAD

**Issue by badosu** [vhakulinen/gnvim#93]
I built gnvim with the latest commit and this happens after coming back from insert mode:

![Screenshot from 2019-08-13 14-57-28](https://user-images.githubusercontent.com/347552/62965109-be048c00-bdda-11e9-8828-721c01cf8537.png)

For some reason the cursor drawing area is squished.

Since I update gnvim weekly this must have been introduced in the last few days.

**Comment by vhakulinen** [comment]
Can you try to [bisect](https://git-scm.com/docs/git-bisect) it?

**Comment by badosu** [comment]
Sure, will do it as soon as I can

**Comment by badosu** [comment]
I can't reproduce the bug anymore, will try if happens again.

**Comment by vhakulinen** [comment]
I managed to reproduce this with coc. Running `CocAction` twice did this, but as it turns out, it is problem with nvim it self. Related coc issue: https://github.com/neoclide/coc.nvim/issues/1011. Not sure if your issue originates from same source.

**Comment by badosu** [comment]
Interesting, given I was trying to reproduce #92.

Indeed, running `:CocList` it seems it's the case.
