### ISSUE TITLE
set colums sometimes causes crash

### ISSUE THREAD

**Issue by agraven** [vhakulinen/gnvim#94]
Invoking `set columns=whatever` sometimes causes GNvim to crash. I can't determine exactly what factor determines whether or not it crashes.

**Comment by vhakulinen** [comment]
Which version of nvim and gnvim?

**Comment by agraven** [comment]
Neovim is the latest from the nightly Ubuntu repository, exact version is `0.4.0+ubuntu4+git201908142038-ebcb9ad-6e51973-d4d251e~ubuntu19.04.1`

The current GNvim version is `gnvim 0.1.4-29-gd4d9d93`

**Comment by smolck** [comment]
@agraven Is this still an issue?

**Comment by agraven** [comment]
Yes. And I still haven't found a reliable way of triggering it, the only consistent observation I've made is that it doesn't seem to happen when the open buffer is empty

**Comment by vhakulinen** [comment]
I suspect this is/was related to the overly complicated and unnecessary data structure gnvim used for its grid representation. The data structure was swapped out in https://github.com/vhakulinen/gnvim/commit/9ba802e3df96b822edda24fb9045e9e2f4d0262b, and that probably fixed this issue too.

**Comment by agraven** [comment]
I'm upgrading to the latest master anyway, so I'll keep an eye out to see if I encounter it again, but let's hope I don't and that it's fixed
